// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: merchant-ips.proto

package merchant_ips_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMerchantIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedBy   string                 `protobuf:"bytes,4,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantIPRequest) Reset() {
	*x = CreateMerchantIPRequest{}
	mi := &file_merchant_ips_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantIPRequest) ProtoMessage() {}

func (x *CreateMerchantIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_ips_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantIPRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantIPRequest) Descriptor() ([]byte, []int) {
	return file_merchant_ips_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMerchantIPRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateMerchantIPRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateMerchantIPRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateMerchantIPRequest) GetSubmittedBy() string {
	if x != nil {
		return x.SubmittedBy
	}
	return ""
}

type MerchantIP struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	IpAddress      string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedBy    string                 `protobuf:"bytes,4,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	ApprovedBy     string                 `protobuf:"bytes,5,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt     string                 `protobuf:"bytes,6,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	RejectedBy     string                 `protobuf:"bytes,7,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	RejectedAt     string                 `protobuf:"bytes,8,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"`
	RejectedReason string                 `protobuf:"bytes,9,opt,name=rejected_reason,json=rejectedReason,proto3" json:"rejected_reason,omitempty"`
	Id             string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MerchantIP) Reset() {
	*x = MerchantIP{}
	mi := &file_merchant_ips_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantIP) ProtoMessage() {}

func (x *MerchantIP) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_ips_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantIP.ProtoReflect.Descriptor instead.
func (*MerchantIP) Descriptor() ([]byte, []int) {
	return file_merchant_ips_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantIP) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantIP) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *MerchantIP) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantIP) GetSubmittedBy() string {
	if x != nil {
		return x.SubmittedBy
	}
	return ""
}

func (x *MerchantIP) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *MerchantIP) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *MerchantIP) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *MerchantIP) GetRejectedAt() string {
	if x != nil {
		return x.RejectedAt
	}
	return ""
}

func (x *MerchantIP) GetRejectedReason() string {
	if x != nil {
		return x.RejectedReason
	}
	return ""
}

func (x *MerchantIP) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantIP) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantIP) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMerchantIPsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantIPsRequest) Reset() {
	*x = GetMerchantIPsRequest{}
	mi := &file_merchant_ips_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantIPsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantIPsRequest) ProtoMessage() {}

func (x *GetMerchantIPsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_ips_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantIPsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantIPsRequest) Descriptor() ([]byte, []int) {
	return file_merchant_ips_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantIPsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMerchantIPsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMerchantIPsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMerchantIPsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantIPsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantIps   []*MerchantIP          `protobuf:"bytes,1,rep,name=merchant_ips,json=merchantIps,proto3" json:"merchant_ips,omitempty"`  // List of merchant IPs
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`    // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`             // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantIPsResponse) Reset() {
	*x = GetMerchantIPsResponse{}
	mi := &file_merchant_ips_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantIPsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantIPsResponse) ProtoMessage() {}

func (x *GetMerchantIPsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_ips_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantIPsResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantIPsResponse) Descriptor() ([]byte, []int) {
	return file_merchant_ips_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantIPsResponse) GetMerchantIps() []*MerchantIP {
	if x != nil {
		return x.MerchantIps
	}
	return nil
}

func (x *GetMerchantIPsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetMerchantIPsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetMerchantIPsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditMerchantIPRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IpAddress      string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ApprovedBy     string                 `protobuf:"bytes,3,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt     string                 `protobuf:"bytes,4,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	RejectedBy     string                 `protobuf:"bytes,5,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	RejectedAt     string                 `protobuf:"bytes,6,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"`
	RejectedReason string                 `protobuf:"bytes,7,opt,name=rejected_reason,json=rejectedReason,proto3" json:"rejected_reason,omitempty"`
	Id             string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMerchantIPRequest) Reset() {
	*x = EditMerchantIPRequest{}
	mi := &file_merchant_ips_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMerchantIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMerchantIPRequest) ProtoMessage() {}

func (x *EditMerchantIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_ips_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMerchantIPRequest.ProtoReflect.Descriptor instead.
func (*EditMerchantIPRequest) Descriptor() ([]byte, []int) {
	return file_merchant_ips_proto_rawDescGZIP(), []int{4}
}

func (x *EditMerchantIPRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *EditMerchantIPRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditMerchantIPRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *EditMerchantIPRequest) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *EditMerchantIPRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *EditMerchantIPRequest) GetRejectedAt() string {
	if x != nil {
		return x.RejectedAt
	}
	return ""
}

func (x *EditMerchantIPRequest) GetRejectedReason() string {
	if x != nil {
		return x.RejectedReason
	}
	return ""
}

func (x *EditMerchantIPRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_merchant_ips_proto protoreflect.FileDescriptor

const file_merchant_ips_proto_rawDesc = "" +
	"\n" +
	"\x12merchant-ips.proto\x12\fmerchant_ips\"\x94\x01\n" +
	"\x17CreateMerchantIPRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fsubmitted_by\x18\x04 \x01(\tR\vsubmittedBy\"\x82\x03\n" +
	"\n" +
	"MerchantIP\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fsubmitted_by\x18\x04 \x01(\tR\vsubmittedBy\x12\x1f\n" +
	"\vapproved_by\x18\x05 \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\x06 \x01(\tR\n" +
	"approvedAt\x12\x1f\n" +
	"\vrejected_by\x18\a \x01(\tR\n" +
	"rejectedBy\x12\x1f\n" +
	"\vrejected_at\x18\b \x01(\tR\n" +
	"rejectedAt\x12'\n" +
	"\x0frejected_reason\x18\t \x01(\tR\x0erejectedReason\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x81\x01\n" +
	"\x15GetMerchantIPsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\"\xb4\x01\n" +
	"\x16GetMerchantIPsResponse\x12;\n" +
	"\fmerchant_ips\x18\x01 \x03(\v2\x18.merchant_ips.MerchantIPR\vmerchantIps\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x8b\x02\n" +
	"\x15EditMerchantIPRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vapproved_by\x18\x03 \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\x04 \x01(\tR\n" +
	"approvedAt\x12\x1f\n" +
	"\vrejected_by\x18\x05 \x01(\tR\n" +
	"rejectedBy\x12\x1f\n" +
	"\vrejected_at\x18\x06 \x01(\tR\n" +
	"rejectedAt\x12'\n" +
	"\x0frejected_reason\x18\a \x01(\tR\x0erejectedReason\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02idB.Z,/proto/merchant_ips_proto;merchant_ips_protob\x06proto3"

var (
	file_merchant_ips_proto_rawDescOnce sync.Once
	file_merchant_ips_proto_rawDescData []byte
)

func file_merchant_ips_proto_rawDescGZIP() []byte {
	file_merchant_ips_proto_rawDescOnce.Do(func() {
		file_merchant_ips_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_ips_proto_rawDesc), len(file_merchant_ips_proto_rawDesc)))
	})
	return file_merchant_ips_proto_rawDescData
}

var file_merchant_ips_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_merchant_ips_proto_goTypes = []any{
	(*CreateMerchantIPRequest)(nil), // 0: merchant_ips.CreateMerchantIPRequest
	(*MerchantIP)(nil),              // 1: merchant_ips.MerchantIP
	(*GetMerchantIPsRequest)(nil),   // 2: merchant_ips.GetMerchantIPsRequest
	(*GetMerchantIPsResponse)(nil),  // 3: merchant_ips.GetMerchantIPsResponse
	(*EditMerchantIPRequest)(nil),   // 4: merchant_ips.EditMerchantIPRequest
}
var file_merchant_ips_proto_depIdxs = []int32{
	1, // 0: merchant_ips.GetMerchantIPsResponse.merchant_ips:type_name -> merchant_ips.MerchantIP
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_ips_proto_init() }
func file_merchant_ips_proto_init() {
	if File_merchant_ips_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_ips_proto_rawDesc), len(file_merchant_ips_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merchant_ips_proto_goTypes,
		DependencyIndexes: file_merchant_ips_proto_depIdxs,
		MessageInfos:      file_merchant_ips_proto_msgTypes,
	}.Build()
	File_merchant_ips_proto = out.File
	file_merchant_ips_proto_goTypes = nil
	file_merchant_ips_proto_depIdxs = nil
}
