// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: channel-fee-bands.proto

package channel_fee_bands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChannelFeeBandsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	MinAmount        string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount        string                 `protobuf:"bytes,5,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ChargeAmount     string                 `protobuf:"bytes,6,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateChannelFeeBandsRequest) Reset() {
	*x = CreateChannelFeeBandsRequest{}
	mi := &file_channel_fee_bands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelFeeBandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelFeeBandsRequest) ProtoMessage() {}

func (x *CreateChannelFeeBandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_fee_bands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelFeeBandsRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelFeeBandsRequest) Descriptor() ([]byte, []int) {
	return file_channel_fee_bands_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChannelFeeBandsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelFeeBandsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateChannelFeeBandsRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *CreateChannelFeeBandsRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *CreateChannelFeeBandsRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *CreateChannelFeeBandsRequest) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

type ChannelFeeBands struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	MinAmount        string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount        string                 `protobuf:"bytes,5,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ChargeAmount     string                 `protobuf:"bytes,6,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	Id               string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChannelFeeBands) Reset() {
	*x = ChannelFeeBands{}
	mi := &file_channel_fee_bands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelFeeBands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelFeeBands) ProtoMessage() {}

func (x *ChannelFeeBands) ProtoReflect() protoreflect.Message {
	mi := &file_channel_fee_bands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelFeeBands.ProtoReflect.Descriptor instead.
func (*ChannelFeeBands) Descriptor() ([]byte, []int) {
	return file_channel_fee_bands_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelFeeBands) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelFeeBands) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChannelFeeBands) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *ChannelFeeBands) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *ChannelFeeBands) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *ChannelFeeBands) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *ChannelFeeBands) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelFeeBands) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChannelFeeBands) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetChannelFeeBandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelFeeBandsRequest) Reset() {
	*x = GetChannelFeeBandsRequest{}
	mi := &file_channel_fee_bands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelFeeBandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelFeeBandsRequest) ProtoMessage() {}

func (x *GetChannelFeeBandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_fee_bands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelFeeBandsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelFeeBandsRequest) Descriptor() ([]byte, []int) {
	return file_channel_fee_bands_proto_rawDescGZIP(), []int{2}
}

func (x *GetChannelFeeBandsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetChannelFeeBandsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetChannelFeeBandsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetChannelFeeBandsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChannelFeeBands []*ChannelFeeBands     `protobuf:"bytes,1,rep,name=channel_fee_bands,json=channelFeeBands,proto3" json:"channel_fee_bands,omitempty"` // List of channel fee bands
	TotalPages      int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                 // Total number of pages
	CurrentPage     int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`              // Current page
	HasMore         bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                          // Whether there are more pages
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetChannelFeeBandsResponse) Reset() {
	*x = GetChannelFeeBandsResponse{}
	mi := &file_channel_fee_bands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelFeeBandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelFeeBandsResponse) ProtoMessage() {}

func (x *GetChannelFeeBandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_fee_bands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelFeeBandsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelFeeBandsResponse) Descriptor() ([]byte, []int) {
	return file_channel_fee_bands_proto_rawDescGZIP(), []int{3}
}

func (x *GetChannelFeeBandsResponse) GetChannelFeeBands() []*ChannelFeeBands {
	if x != nil {
		return x.ChannelFeeBands
	}
	return nil
}

func (x *GetChannelFeeBandsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetChannelFeeBandsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetChannelFeeBandsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditChannelFeeBandsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,2,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	MinAmount        string                 `protobuf:"bytes,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount        string                 `protobuf:"bytes,4,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ChargeAmount     string                 `protobuf:"bytes,5,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Id               string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditChannelFeeBandsRequest) Reset() {
	*x = EditChannelFeeBandsRequest{}
	mi := &file_channel_fee_bands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditChannelFeeBandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditChannelFeeBandsRequest) ProtoMessage() {}

func (x *EditChannelFeeBandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_fee_bands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditChannelFeeBandsRequest.ProtoReflect.Descriptor instead.
func (*EditChannelFeeBandsRequest) Descriptor() ([]byte, []int) {
	return file_channel_fee_bands_proto_rawDescGZIP(), []int{4}
}

func (x *EditChannelFeeBandsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditChannelFeeBandsRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *EditChannelFeeBandsRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *EditChannelFeeBandsRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *EditChannelFeeBandsRequest) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *EditChannelFeeBandsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditChannelFeeBandsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_channel_fee_bands_proto protoreflect.FileDescriptor

const file_channel_fee_bands_proto_rawDesc = "" +
	"\n" +
	"\x17channel-fee-bands.proto\x12\x11channel_fee_bands\"\xdb\x01\n" +
	"\x1cCreateChannelFeeBandsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x05 \x01(\tR\tmaxAmount\x12#\n" +
	"\rcharge_amount\x18\x06 \x01(\tR\fchargeAmount\"\x9c\x02\n" +
	"\x0fChannelFeeBands\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x05 \x01(\tR\tmaxAmount\x12#\n" +
	"\rcharge_amount\x18\x06 \x01(\tR\fchargeAmount\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"o\n" +
	"\x19GetChannelFeeBandsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xcb\x01\n" +
	"\x1aGetChannelFeeBandsResponse\x12N\n" +
	"\x11channel_fee_bands\x18\x01 \x03(\v2\".channel_fee_bands.ChannelFeeBandsR\x0fchannelFeeBands\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xe9\x01\n" +
	"\x1aEditChannelFeeBandsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12payment_channel_id\x18\x02 \x01(\tR\x10paymentChannelId\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x03 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x04 \x01(\tR\tmaxAmount\x12#\n" +
	"\rcharge_amount\x18\x05 \x01(\tR\fchargeAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02idB,Z*/proto/channel_fee_bands;channel_fee_bandsb\x06proto3"

var (
	file_channel_fee_bands_proto_rawDescOnce sync.Once
	file_channel_fee_bands_proto_rawDescData []byte
)

func file_channel_fee_bands_proto_rawDescGZIP() []byte {
	file_channel_fee_bands_proto_rawDescOnce.Do(func() {
		file_channel_fee_bands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_fee_bands_proto_rawDesc), len(file_channel_fee_bands_proto_rawDesc)))
	})
	return file_channel_fee_bands_proto_rawDescData
}

var file_channel_fee_bands_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_channel_fee_bands_proto_goTypes = []any{
	(*CreateChannelFeeBandsRequest)(nil), // 0: channel_fee_bands.CreateChannelFeeBandsRequest
	(*ChannelFeeBands)(nil),              // 1: channel_fee_bands.ChannelFeeBands
	(*GetChannelFeeBandsRequest)(nil),    // 2: channel_fee_bands.GetChannelFeeBandsRequest
	(*GetChannelFeeBandsResponse)(nil),   // 3: channel_fee_bands.GetChannelFeeBandsResponse
	(*EditChannelFeeBandsRequest)(nil),   // 4: channel_fee_bands.EditChannelFeeBandsRequest
}
var file_channel_fee_bands_proto_depIdxs = []int32{
	1, // 0: channel_fee_bands.GetChannelFeeBandsResponse.channel_fee_bands:type_name -> channel_fee_bands.ChannelFeeBands
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_channel_fee_bands_proto_init() }
func file_channel_fee_bands_proto_init() {
	if File_channel_fee_bands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_fee_bands_proto_rawDesc), len(file_channel_fee_bands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_channel_fee_bands_proto_goTypes,
		DependencyIndexes: file_channel_fee_bands_proto_depIdxs,
		MessageInfos:      file_channel_fee_bands_proto_msgTypes,
	}.Build()
	File_channel_fee_bands_proto = out.File
	file_channel_fee_bands_proto_goTypes = nil
	file_channel_fee_bands_proto_depIdxs = nil
}
