// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: providers.proto

package providers_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_providers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateProviderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_providers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{1}
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Provider) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Provider) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersRequest) Reset() {
	*x = GetProvidersRequest{}
	mi := &file_providers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersRequest) ProtoMessage() {}

func (x *GetProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetProvidersRequest) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{2}
}

func (x *GetProvidersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProvidersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetProvidersRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type GetProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`                         // List of providers
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`    // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`             // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersResponse) Reset() {
	*x = GetProvidersResponse{}
	mi := &file_providers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersResponse) ProtoMessage() {}

func (x *GetProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetProvidersResponse) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{3}
}

func (x *GetProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *GetProvidersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetProvidersResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetProvidersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProviderRequest) Reset() {
	*x = EditProviderRequest{}
	mi := &file_providers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProviderRequest) ProtoMessage() {}

func (x *EditProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_providers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProviderRequest.ProtoReflect.Descriptor instead.
func (*EditProviderRequest) Descriptor() ([]byte, []int) {
	return file_providers_proto_rawDescGZIP(), []int{4}
}

func (x *EditProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditProviderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditProviderRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_providers_proto protoreflect.FileDescriptor

const file_providers_proto_rawDesc = "" +
	"\n" +
	"\x0fproviders.proto\x12\x0fproviders_proto\"W\n" +
	"\x15CreateProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x98\x01\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\"k\n" +
	"\x13GetProvidersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\"\xae\x01\n" +
	"\x14GetProvidersResponse\x127\n" +
	"\tproviders\x18\x01 \x03(\v2\x19.providers_proto.ProviderR\tproviders\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"e\n" +
	"\x13EditProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04codeB(Z&/proto/providers_proto;providers_protob\x06proto3"

var (
	file_providers_proto_rawDescOnce sync.Once
	file_providers_proto_rawDescData []byte
)

func file_providers_proto_rawDescGZIP() []byte {
	file_providers_proto_rawDescOnce.Do(func() {
		file_providers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_providers_proto_rawDesc), len(file_providers_proto_rawDesc)))
	})
	return file_providers_proto_rawDescData
}

var file_providers_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_providers_proto_goTypes = []any{
	(*CreateProviderRequest)(nil), // 0: providers_proto.CreateProviderRequest
	(*Provider)(nil),              // 1: providers_proto.Provider
	(*GetProvidersRequest)(nil),   // 2: providers_proto.GetProvidersRequest
	(*GetProvidersResponse)(nil),  // 3: providers_proto.GetProvidersResponse
	(*EditProviderRequest)(nil),   // 4: providers_proto.EditProviderRequest
}
var file_providers_proto_depIdxs = []int32{
	1, // 0: providers_proto.GetProvidersResponse.providers:type_name -> providers_proto.Provider
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_providers_proto_init() }
func file_providers_proto_init() {
	if File_providers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_providers_proto_rawDesc), len(file_providers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_providers_proto_goTypes,
		DependencyIndexes: file_providers_proto_depIdxs,
		MessageInfos:      file_providers_proto_msgTypes,
	}.Build()
	File_providers_proto = out.File
	file_providers_proto_goTypes = nil
	file_providers_proto_depIdxs = nil
}
