// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: payment-channels.proto

package payment_channels_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentChannelRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionId       string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TransactionTypeId    string                 `protobuf:"bytes,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId string                 `protobuf:"bytes,5,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	FeeType              string                 `protobuf:"bytes,6,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"`
	ProviderFee          string                 `protobuf:"bytes,7,opt,name=provider_fee,json=providerFee,proto3" json:"provider_fee,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentChannelRequest) Reset() {
	*x = CreatePaymentChannelRequest{}
	mi := &file_payment_channels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentChannelRequest) ProtoMessage() {}

func (x *CreatePaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_channels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_payment_channels_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetFeeType() string {
	if x != nil {
		return x.FeeType
	}
	return ""
}

func (x *CreatePaymentChannelRequest) GetProviderFee() string {
	if x != nil {
		return x.ProviderFee
	}
	return ""
}

type PaymentChannel struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionId       string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TransactionTypeId    string                 `protobuf:"bytes,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId string                 `protobuf:"bytes,5,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	FeeType              string                 `protobuf:"bytes,6,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"`
	ProviderFee          string                 `protobuf:"bytes,7,opt,name=provider_fee,json=providerFee,proto3" json:"provider_fee,omitempty"`
	Id                   string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Logo                 string                 `protobuf:"bytes,11,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentChannel) Reset() {
	*x = PaymentChannel{}
	mi := &file_payment_channels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentChannel) ProtoMessage() {}

func (x *PaymentChannel) ProtoReflect() protoreflect.Message {
	mi := &file_payment_channels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentChannel.ProtoReflect.Descriptor instead.
func (*PaymentChannel) Descriptor() ([]byte, []int) {
	return file_payment_channels_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentChannel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentChannel) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *PaymentChannel) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *PaymentChannel) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *PaymentChannel) GetFeeType() string {
	if x != nil {
		return x.FeeType
	}
	return ""
}

func (x *PaymentChannel) GetProviderFee() string {
	if x != nil {
		return x.ProviderFee
	}
	return ""
}

func (x *PaymentChannel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentChannel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentChannel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentChannel) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

type GetPaymentChannelsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Page                 int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery          string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	SubscriptionId       string                 `protobuf:"bytes,4,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TransactionTypeId    string                 `protobuf:"bytes,5,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId string                 `protobuf:"bytes,6,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	FeeType              string                 `protobuf:"bytes,7,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"`
	ProviderFee          string                 `protobuf:"bytes,8,opt,name=provider_fee,json=providerFee,proto3" json:"provider_fee,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPaymentChannelsRequest) Reset() {
	*x = GetPaymentChannelsRequest{}
	mi := &file_payment_channels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentChannelsRequest) ProtoMessage() {}

func (x *GetPaymentChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_channels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentChannelsRequest) Descriptor() ([]byte, []int) {
	return file_payment_channels_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentChannelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPaymentChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPaymentChannelsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetPaymentChannelsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetPaymentChannelsRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *GetPaymentChannelsRequest) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *GetPaymentChannelsRequest) GetFeeType() string {
	if x != nil {
		return x.FeeType
	}
	return ""
}

func (x *GetPaymentChannelsRequest) GetProviderFee() string {
	if x != nil {
		return x.ProviderFee
	}
	return ""
}

type GetPaymentChannelsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentChannel []*PaymentChannel      `protobuf:"bytes,1,rep,name=payment_channel,json=paymentChannel,proto3" json:"payment_channel,omitempty"` // List of payment channels
	TotalPages     int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`            // Total number of pages
	CurrentPage    int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`         // Current page
	HasMore        bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                     // Whether there are more pages
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentChannelsResponse) Reset() {
	*x = GetPaymentChannelsResponse{}
	mi := &file_payment_channels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentChannelsResponse) ProtoMessage() {}

func (x *GetPaymentChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_channels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentChannelsResponse) Descriptor() ([]byte, []int) {
	return file_payment_channels_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentChannelsResponse) GetPaymentChannel() []*PaymentChannel {
	if x != nil {
		return x.PaymentChannel
	}
	return nil
}

func (x *GetPaymentChannelsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetPaymentChannelsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetPaymentChannelsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditPaymentChannelRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionId       string                 `protobuf:"bytes,4,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	TransactionTypeId    string                 `protobuf:"bytes,5,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId string                 `protobuf:"bytes,6,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	FeeType              string                 `protobuf:"bytes,7,opt,name=fee_type,json=feeType,proto3" json:"fee_type,omitempty"`
	ProviderFee          string                 `protobuf:"bytes,8,opt,name=provider_fee,json=providerFee,proto3" json:"provider_fee,omitempty"`
	Id                   string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EditPaymentChannelRequest) Reset() {
	*x = EditPaymentChannelRequest{}
	mi := &file_payment_channels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPaymentChannelRequest) ProtoMessage() {}

func (x *EditPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_channels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*EditPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_payment_channels_proto_rawDescGZIP(), []int{4}
}

func (x *EditPaymentChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetFeeType() string {
	if x != nil {
		return x.FeeType
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetProviderFee() string {
	if x != nil {
		return x.ProviderFee
	}
	return ""
}

func (x *EditPaymentChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_payment_channels_proto protoreflect.FileDescriptor

const file_payment_channels_proto_rawDesc = "" +
	"\n" +
	"\x16payment-channels.proto\x12\x16payment_channels_proto\"\x97\x02\n" +
	"\x1bCreatePaymentChannelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x05 \x01(\tR\x14subTransactionTypeId\x12\x19\n" +
	"\bfee_type\x18\x06 \x01(\tR\afeeType\x12!\n" +
	"\fprovider_fee\x18\a \x01(\tR\vproviderFee\"\xec\x02\n" +
	"\x0ePaymentChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x05 \x01(\tR\x14subTransactionTypeId\x12\x19\n" +
	"\bfee_type\x18\x06 \x01(\tR\afeeType\x12!\n" +
	"\fprovider_fee\x18\a \x01(\tR\vproviderFee\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04logo\x18\v \x01(\tR\x04logo\"\xbd\x02\n" +
	"\x19GetPaymentChannelsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x12'\n" +
	"\x0fsubscription_id\x18\x04 \x01(\tR\x0esubscriptionId\x12.\n" +
	"\x13transaction_type_id\x18\x05 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x06 \x01(\tR\x14subTransactionTypeId\x12\x19\n" +
	"\bfee_type\x18\a \x01(\tR\afeeType\x12!\n" +
	"\fprovider_fee\x18\b \x01(\tR\vproviderFee\"\xcc\x01\n" +
	"\x1aGetPaymentChannelsResponse\x12O\n" +
	"\x0fpayment_channel\x18\x01 \x03(\v2&.payment_channels_proto.PaymentChannelR\x0epaymentChannel\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xa5\x02\n" +
	"\x19EditPaymentChannelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fsubscription_id\x18\x04 \x01(\tR\x0esubscriptionId\x12.\n" +
	"\x13transaction_type_id\x18\x05 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x06 \x01(\tR\x14subTransactionTypeId\x12\x19\n" +
	"\bfee_type\x18\a \x01(\tR\afeeType\x12!\n" +
	"\fprovider_fee\x18\b \x01(\tR\vproviderFee\x12\x0e\n" +
	"\x02id\x18\t \x01(\tR\x02idB6Z4/proto/payment_channels_proto;payment_channels_protob\x06proto3"

var (
	file_payment_channels_proto_rawDescOnce sync.Once
	file_payment_channels_proto_rawDescData []byte
)

func file_payment_channels_proto_rawDescGZIP() []byte {
	file_payment_channels_proto_rawDescOnce.Do(func() {
		file_payment_channels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_channels_proto_rawDesc), len(file_payment_channels_proto_rawDesc)))
	})
	return file_payment_channels_proto_rawDescData
}

var file_payment_channels_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payment_channels_proto_goTypes = []any{
	(*CreatePaymentChannelRequest)(nil), // 0: payment_channels_proto.CreatePaymentChannelRequest
	(*PaymentChannel)(nil),              // 1: payment_channels_proto.PaymentChannel
	(*GetPaymentChannelsRequest)(nil),   // 2: payment_channels_proto.GetPaymentChannelsRequest
	(*GetPaymentChannelsResponse)(nil),  // 3: payment_channels_proto.GetPaymentChannelsResponse
	(*EditPaymentChannelRequest)(nil),   // 4: payment_channels_proto.EditPaymentChannelRequest
}
var file_payment_channels_proto_depIdxs = []int32{
	1, // 0: payment_channels_proto.GetPaymentChannelsResponse.payment_channel:type_name -> payment_channels_proto.PaymentChannel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_channels_proto_init() }
func file_payment_channels_proto_init() {
	if File_payment_channels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_channels_proto_rawDesc), len(file_payment_channels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_channels_proto_goTypes,
		DependencyIndexes: file_payment_channels_proto_depIdxs,
		MessageInfos:      file_payment_channels_proto_msgTypes,
	}.Build()
	File_payment_channels_proto = out.File
	file_payment_channels_proto_goTypes = nil
	file_payment_channels_proto_depIdxs = nil
}
