// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: prefixes.proto

package prefixes_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrefixRequest) Reset() {
	*x = CreatePrefixRequest{}
	mi := &file_prefixes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrefixRequest) ProtoMessage() {}

func (x *CreatePrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrefixRequest.ProtoReflect.Descriptor instead.
func (*CreatePrefixRequest) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePrefixRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePrefixRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Prefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prefix) Reset() {
	*x = Prefix{}
	mi := &file_prefixes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefix) ProtoMessage() {}

func (x *Prefix) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefix.ProtoReflect.Descriptor instead.
func (*Prefix) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{1}
}

func (x *Prefix) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prefix) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Prefix) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Prefix) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Prefix) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetPrefixesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefixesRequest) Reset() {
	*x = GetPrefixesRequest{}
	mi := &file_prefixes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixesRequest) ProtoMessage() {}

func (x *GetPrefixesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixesRequest.ProtoReflect.Descriptor instead.
func (*GetPrefixesRequest) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{2}
}

func (x *GetPrefixesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPrefixesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPrefixesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetPrefixesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []*Prefix              `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`                           // List of prefixes
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`    // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`             // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrefixesResponse) Reset() {
	*x = GetPrefixesResponse{}
	mi := &file_prefixes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixesResponse) ProtoMessage() {}

func (x *GetPrefixesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixesResponse.ProtoReflect.Descriptor instead.
func (*GetPrefixesResponse) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{3}
}

func (x *GetPrefixesResponse) GetPrefixes() []*Prefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *GetPrefixesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetPrefixesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetPrefixesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPrefixRequest) Reset() {
	*x = EditPrefixRequest{}
	mi := &file_prefixes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPrefixRequest) ProtoMessage() {}

func (x *EditPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPrefixRequest.ProtoReflect.Descriptor instead.
func (*EditPrefixRequest) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{4}
}

func (x *EditPrefixRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditPrefixRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditPrefixRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PrefixPaymentChannel struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrefixId           string                 `protobuf:"bytes,2,opt,name=prefix_id,json=prefixId,proto3" json:"prefix_id,omitempty"`
	PaymentChannelId   string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PaymentChannelName string                 `protobuf:"bytes,6,opt,name=payment_channel_name,json=paymentChannelName,proto3" json:"payment_channel_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrefixPaymentChannel) Reset() {
	*x = PrefixPaymentChannel{}
	mi := &file_prefixes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixPaymentChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixPaymentChannel) ProtoMessage() {}

func (x *PrefixPaymentChannel) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixPaymentChannel.ProtoReflect.Descriptor instead.
func (*PrefixPaymentChannel) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{5}
}

func (x *PrefixPaymentChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrefixPaymentChannel) GetPrefixId() string {
	if x != nil {
		return x.PrefixId
	}
	return ""
}

func (x *PrefixPaymentChannel) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *PrefixPaymentChannel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PrefixPaymentChannel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PrefixPaymentChannel) GetPaymentChannelName() string {
	if x != nil {
		return x.PaymentChannelName
	}
	return ""
}

type CreatePrefixPaymentChannelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrefixId         string                 `protobuf:"bytes,1,opt,name=prefix_id,json=prefixId,proto3" json:"prefix_id,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,2,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePrefixPaymentChannelRequest) Reset() {
	*x = CreatePrefixPaymentChannelRequest{}
	mi := &file_prefixes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrefixPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrefixPaymentChannelRequest) ProtoMessage() {}

func (x *CreatePrefixPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrefixPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*CreatePrefixPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePrefixPaymentChannelRequest) GetPrefixId() string {
	if x != nil {
		return x.PrefixId
	}
	return ""
}

func (x *CreatePrefixPaymentChannelRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

type GetPrefixPaymentChannelsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PrefixId         string                 `protobuf:"bytes,1,opt,name=prefix_id,json=prefixId,proto3" json:"prefix_id,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,2,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	Page             int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPrefixPaymentChannelsRequest) Reset() {
	*x = GetPrefixPaymentChannelsRequest{}
	mi := &file_prefixes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixPaymentChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixPaymentChannelsRequest) ProtoMessage() {}

func (x *GetPrefixPaymentChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixPaymentChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetPrefixPaymentChannelsRequest) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{7}
}

func (x *GetPrefixPaymentChannelsRequest) GetPrefixId() string {
	if x != nil {
		return x.PrefixId
	}
	return ""
}

func (x *GetPrefixPaymentChannelsRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *GetPrefixPaymentChannelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPrefixPaymentChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetPrefixPaymentChannelsResponse struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	PrefixPaymentChannels []*PrefixPaymentChannel `protobuf:"bytes,1,rep,name=prefix_payment_channels,json=prefixPaymentChannels,proto3" json:"prefix_payment_channels,omitempty"`
	TotalPages            int32                   `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage           int32                   `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	HasMore               bool                    `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetPrefixPaymentChannelsResponse) Reset() {
	*x = GetPrefixPaymentChannelsResponse{}
	mi := &file_prefixes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrefixPaymentChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrefixPaymentChannelsResponse) ProtoMessage() {}

func (x *GetPrefixPaymentChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prefixes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrefixPaymentChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetPrefixPaymentChannelsResponse) Descriptor() ([]byte, []int) {
	return file_prefixes_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrefixPaymentChannelsResponse) GetPrefixPaymentChannels() []*PrefixPaymentChannel {
	if x != nil {
		return x.PrefixPaymentChannels
	}
	return nil
}

func (x *GetPrefixPaymentChannelsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetPrefixPaymentChannelsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetPrefixPaymentChannelsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_prefixes_proto protoreflect.FileDescriptor

const file_prefixes_proto_rawDesc = "" +
	"\n" +
	"\x0eprefixes.proto\x12\x0eprefixes_proto\"A\n" +
	"\x13CreatePrefixRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x82\x01\n" +
	"\x06Prefix\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"h\n" +
	"\x12GetPrefixesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xa8\x01\n" +
	"\x13GetPrefixesResponse\x122\n" +
	"\bprefixes\x18\x01 \x03(\v2\x16.prefixes_proto.PrefixR\bprefixes\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"O\n" +
	"\x11EditPrefixRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xe5\x01\n" +
	"\x14PrefixPaymentChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tprefix_id\x18\x02 \x01(\tR\bprefixId\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x120\n" +
	"\x14payment_channel_name\x18\x06 \x01(\tR\x12paymentChannelName\"n\n" +
	"!CreatePrefixPaymentChannelRequest\x12\x1b\n" +
	"\tprefix_id\x18\x01 \x01(\tR\bprefixId\x12,\n" +
	"\x12payment_channel_id\x18\x02 \x01(\tR\x10paymentChannelId\"\x9d\x01\n" +
	"\x1fGetPrefixPaymentChannelsRequest\x12\x1b\n" +
	"\tprefix_id\x18\x01 \x01(\tR\bprefixId\x12,\n" +
	"\x12payment_channel_id\x18\x02 \x01(\tR\x10paymentChannelId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xdf\x01\n" +
	" GetPrefixPaymentChannelsResponse\x12\\\n" +
	"\x17prefix_payment_channels\x18\x01 \x03(\v2$.prefixes_proto.PrefixPaymentChannelR\x15prefixPaymentChannels\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMoreB&Z$/proto/prefixes_proto;prefixes_protob\x06proto3"

var (
	file_prefixes_proto_rawDescOnce sync.Once
	file_prefixes_proto_rawDescData []byte
)

func file_prefixes_proto_rawDescGZIP() []byte {
	file_prefixes_proto_rawDescOnce.Do(func() {
		file_prefixes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_prefixes_proto_rawDesc), len(file_prefixes_proto_rawDesc)))
	})
	return file_prefixes_proto_rawDescData
}

var file_prefixes_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_prefixes_proto_goTypes = []any{
	(*CreatePrefixRequest)(nil),               // 0: prefixes_proto.CreatePrefixRequest
	(*Prefix)(nil),                            // 1: prefixes_proto.Prefix
	(*GetPrefixesRequest)(nil),                // 2: prefixes_proto.GetPrefixesRequest
	(*GetPrefixesResponse)(nil),               // 3: prefixes_proto.GetPrefixesResponse
	(*EditPrefixRequest)(nil),                 // 4: prefixes_proto.EditPrefixRequest
	(*PrefixPaymentChannel)(nil),              // 5: prefixes_proto.PrefixPaymentChannel
	(*CreatePrefixPaymentChannelRequest)(nil), // 6: prefixes_proto.CreatePrefixPaymentChannelRequest
	(*GetPrefixPaymentChannelsRequest)(nil),   // 7: prefixes_proto.GetPrefixPaymentChannelsRequest
	(*GetPrefixPaymentChannelsResponse)(nil),  // 8: prefixes_proto.GetPrefixPaymentChannelsResponse
}
var file_prefixes_proto_depIdxs = []int32{
	1, // 0: prefixes_proto.GetPrefixesResponse.prefixes:type_name -> prefixes_proto.Prefix
	5, // 1: prefixes_proto.GetPrefixPaymentChannelsResponse.prefix_payment_channels:type_name -> prefixes_proto.PrefixPaymentChannel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_prefixes_proto_init() }
func file_prefixes_proto_init() {
	if File_prefixes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_prefixes_proto_rawDesc), len(file_prefixes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prefixes_proto_goTypes,
		DependencyIndexes: file_prefixes_proto_depIdxs,
		MessageInfos:      file_prefixes_proto_msgTypes,
	}.Build()
	File_prefixes_proto = out.File
	file_prefixes_proto_goTypes = nil
	file_prefixes_proto_depIdxs = nil
}
