// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: payment-services.proto

package payment_services_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentServiceRequest) Reset() {
	*x = CreatePaymentServiceRequest{}
	mi := &file_payment_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentServiceRequest) ProtoMessage() {}

func (x *CreatePaymentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentServiceRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentServiceRequest) Descriptor() ([]byte, []int) {
	return file_payment_services_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePaymentServiceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PaymentService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentService) Reset() {
	*x = PaymentService{}
	mi := &file_payment_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentService) ProtoMessage() {}

func (x *PaymentService) ProtoReflect() protoreflect.Message {
	mi := &file_payment_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentService.ProtoReflect.Descriptor instead.
func (*PaymentService) Descriptor() ([]byte, []int) {
	return file_payment_services_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentService) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentService) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *PaymentService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentService) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentService) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetPaymentServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentServicesRequest) Reset() {
	*x = GetPaymentServicesRequest{}
	mi := &file_payment_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentServicesRequest) ProtoMessage() {}

func (x *GetPaymentServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentServicesRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentServicesRequest) Descriptor() ([]byte, []int) {
	return file_payment_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentServicesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPaymentServicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetPaymentServicesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetPaymentServicesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentService []*PaymentService      `protobuf:"bytes,1,rep,name=payment_service,json=paymentService,proto3" json:"payment_service,omitempty"` // List of payment services
	TotalPages     int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`            // Total number of pages
	CurrentPage    int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`         // Current page
	HasMore        bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                     // Whether there are more pages
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentServicesResponse) Reset() {
	*x = GetPaymentServicesResponse{}
	mi := &file_payment_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentServicesResponse) ProtoMessage() {}

func (x *GetPaymentServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentServicesResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentServicesResponse) Descriptor() ([]byte, []int) {
	return file_payment_services_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentServicesResponse) GetPaymentService() []*PaymentService {
	if x != nil {
		return x.PaymentService
	}
	return nil
}

func (x *GetPaymentServicesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetPaymentServicesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetPaymentServicesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditPaymentServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPaymentServiceRequest) Reset() {
	*x = EditPaymentServiceRequest{}
	mi := &file_payment_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPaymentServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPaymentServiceRequest) ProtoMessage() {}

func (x *EditPaymentServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPaymentServiceRequest.ProtoReflect.Descriptor instead.
func (*EditPaymentServiceRequest) Descriptor() ([]byte, []int) {
	return file_payment_services_proto_rawDescGZIP(), []int{4}
}

func (x *EditPaymentServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditPaymentServiceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditPaymentServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_payment_services_proto protoreflect.FileDescriptor

const file_payment_services_proto_rawDesc = "" +
	"\n" +
	"\x16payment-services.proto\x12\x16payment_services_proto\"I\n" +
	"\x1bCreatePaymentServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x9e\x01\n" +
	"\x0ePaymentService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"o\n" +
	"\x19GetPaymentServicesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xcc\x01\n" +
	"\x1aGetPaymentServicesResponse\x12O\n" +
	"\x0fpayment_service\x18\x01 \x03(\v2&.payment_services_proto.PaymentServiceR\x0epaymentService\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"W\n" +
	"\x19EditPaymentServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02idB6Z4/proto/payment_services_proto;payment_services_protob\x06proto3"

var (
	file_payment_services_proto_rawDescOnce sync.Once
	file_payment_services_proto_rawDescData []byte
)

func file_payment_services_proto_rawDescGZIP() []byte {
	file_payment_services_proto_rawDescOnce.Do(func() {
		file_payment_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_services_proto_rawDesc), len(file_payment_services_proto_rawDesc)))
	})
	return file_payment_services_proto_rawDescData
}

var file_payment_services_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payment_services_proto_goTypes = []any{
	(*CreatePaymentServiceRequest)(nil), // 0: payment_services_proto.CreatePaymentServiceRequest
	(*PaymentService)(nil),              // 1: payment_services_proto.PaymentService
	(*GetPaymentServicesRequest)(nil),   // 2: payment_services_proto.GetPaymentServicesRequest
	(*GetPaymentServicesResponse)(nil),  // 3: payment_services_proto.GetPaymentServicesResponse
	(*EditPaymentServiceRequest)(nil),   // 4: payment_services_proto.EditPaymentServiceRequest
}
var file_payment_services_proto_depIdxs = []int32{
	1, // 0: payment_services_proto.GetPaymentServicesResponse.payment_service:type_name -> payment_services_proto.PaymentService
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_services_proto_init() }
func file_payment_services_proto_init() {
	if File_payment_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_services_proto_rawDesc), len(file_payment_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_services_proto_goTypes,
		DependencyIndexes: file_payment_services_proto_depIdxs,
		MessageInfos:      file_payment_services_proto_msgTypes,
	}.Build()
	File_payment_services_proto = out.File
	file_payment_services_proto_goTypes = nil
	file_payment_services_proto_depIdxs = nil
}
