// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: fee-profiles.proto

package fee_profiles_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFeeProfileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	PaymentChannelId     string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	TransactionTypeId    string                 `protobuf:"bytes,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId string                 `protobuf:"bytes,5,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	Status               string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ChargeAmount         string                 `protobuf:"bytes,7,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	ApprovalStatus       string                 `protobuf:"bytes,8,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	ApprovedBy           string                 `protobuf:"bytes,9,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt           string                 `protobuf:"bytes,10,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	RejectedBy           string                 `protobuf:"bytes,11,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	RejectedReason       string                 `protobuf:"bytes,13,opt,name=rejected_reason,json=rejectedReason,proto3" json:"rejected_reason,omitempty"`
	CalculationMode      string                 `protobuf:"bytes,14,opt,name=calculation_mode,json=calculationMode,proto3" json:"calculation_mode,omitempty"`
	ChargeType           string                 `protobuf:"bytes,15,opt,name=charge_type,json=chargeType,proto3" json:"charge_type,omitempty"`
	MinimumFee           string                 `protobuf:"bytes,16,opt,name=minimum_fee,json=minimumFee,proto3" json:"minimum_fee,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateFeeProfileRequest) Reset() {
	*x = CreateFeeProfileRequest{}
	mi := &file_fee_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFeeProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeeProfileRequest) ProtoMessage() {}

func (x *CreateFeeProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fee_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeeProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateFeeProfileRequest) Descriptor() ([]byte, []int) {
	return file_fee_profiles_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFeeProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetRejectedReason() string {
	if x != nil {
		return x.RejectedReason
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetCalculationMode() string {
	if x != nil {
		return x.CalculationMode
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetChargeType() string {
	if x != nil {
		return x.ChargeType
	}
	return ""
}

func (x *CreateFeeProfileRequest) GetMinimumFee() string {
	if x != nil {
		return x.MinimumFee
	}
	return ""
}

type FeeProfile struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                   string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	PaymentChannelId       string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	TransactionTypeId      string                 `protobuf:"bytes,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId   string                 `protobuf:"bytes,5,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	Status                 string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ChargeAmount           string                 `protobuf:"bytes,7,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	ApprovalStatus         string                 `protobuf:"bytes,8,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	ApprovedBy             string                 `protobuf:"bytes,9,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt             string                 `protobuf:"bytes,10,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	RejectedBy             string                 `protobuf:"bytes,11,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	RejectedReason         string                 `protobuf:"bytes,13,opt,name=rejected_reason,json=rejectedReason,proto3" json:"rejected_reason,omitempty"`
	CalculationMode        string                 `protobuf:"bytes,14,opt,name=calculation_mode,json=calculationMode,proto3" json:"calculation_mode,omitempty"`
	Id                     string                 `protobuf:"bytes,15,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt              string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              string                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PaymentChannelName     string                 `protobuf:"bytes,18,opt,name=payment_channel_name,json=paymentChannelName,proto3" json:"payment_channel_name,omitempty"`
	TransactionTypeName    string                 `protobuf:"bytes,19,opt,name=transaction_type_name,json=transactionTypeName,proto3" json:"transaction_type_name,omitempty"`
	SubTransactionTypeName string                 `protobuf:"bytes,20,opt,name=sub_transaction_type_name,json=subTransactionTypeName,proto3" json:"sub_transaction_type_name,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FeeProfile) Reset() {
	*x = FeeProfile{}
	mi := &file_fee_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeProfile) ProtoMessage() {}

func (x *FeeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_fee_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeProfile.ProtoReflect.Descriptor instead.
func (*FeeProfile) Descriptor() ([]byte, []int) {
	return file_fee_profiles_proto_rawDescGZIP(), []int{1}
}

func (x *FeeProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeeProfile) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FeeProfile) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *FeeProfile) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *FeeProfile) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *FeeProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FeeProfile) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *FeeProfile) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *FeeProfile) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *FeeProfile) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *FeeProfile) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *FeeProfile) GetRejectedReason() string {
	if x != nil {
		return x.RejectedReason
	}
	return ""
}

func (x *FeeProfile) GetCalculationMode() string {
	if x != nil {
		return x.CalculationMode
	}
	return ""
}

func (x *FeeProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeeProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FeeProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FeeProfile) GetPaymentChannelName() string {
	if x != nil {
		return x.PaymentChannelName
	}
	return ""
}

func (x *FeeProfile) GetTransactionTypeName() string {
	if x != nil {
		return x.TransactionTypeName
	}
	return ""
}

func (x *FeeProfile) GetSubTransactionTypeName() string {
	if x != nil {
		return x.SubTransactionTypeName
	}
	return ""
}

type GetFeeProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=searchQuery,proto3" json:"searchQuery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeProfilesRequest) Reset() {
	*x = GetFeeProfilesRequest{}
	mi := &file_fee_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeProfilesRequest) ProtoMessage() {}

func (x *GetFeeProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fee_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetFeeProfilesRequest) Descriptor() ([]byte, []int) {
	return file_fee_profiles_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeeProfilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFeeProfilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetFeeProfilesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetFeeProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeProfile    []*FeeProfile          `protobuf:"bytes,1,rep,name=fee_profile,json=feeProfile,proto3" json:"fee_profile,omitempty"` // List of fee profiles
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`                  // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"`                // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`                        // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeProfilesResponse) Reset() {
	*x = GetFeeProfilesResponse{}
	mi := &file_fee_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeProfilesResponse) ProtoMessage() {}

func (x *GetFeeProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fee_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetFeeProfilesResponse) Descriptor() ([]byte, []int) {
	return file_fee_profiles_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeeProfilesResponse) GetFeeProfile() []*FeeProfile {
	if x != nil {
		return x.FeeProfile
	}
	return nil
}

func (x *GetFeeProfilesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetFeeProfilesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetFeeProfilesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditFeeProfileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	PaymentChannelId     string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	TransactionTypeId    string                 `protobuf:"bytes,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	SubTransactionTypeId string                 `protobuf:"bytes,5,opt,name=sub_transaction_type_id,json=subTransactionTypeId,proto3" json:"sub_transaction_type_id,omitempty"`
	Status               string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ChargeAmount         string                 `protobuf:"bytes,7,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	ApprovalStatus       string                 `protobuf:"bytes,8,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	ApprovedBy           string                 `protobuf:"bytes,9,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt           string                 `protobuf:"bytes,10,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	RejectedBy           string                 `protobuf:"bytes,11,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	RejectedReason       string                 `protobuf:"bytes,12,opt,name=rejected_reason,json=rejectedReason,proto3" json:"rejected_reason,omitempty"`
	Id                   string                 `protobuf:"bytes,13,opt,name=id,proto3" json:"id,omitempty"`
	CalculationMode      string                 `protobuf:"bytes,14,opt,name=calculation_mode,json=calculationMode,proto3" json:"calculation_mode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EditFeeProfileRequest) Reset() {
	*x = EditFeeProfileRequest{}
	mi := &file_fee_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditFeeProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditFeeProfileRequest) ProtoMessage() {}

func (x *EditFeeProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fee_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditFeeProfileRequest.ProtoReflect.Descriptor instead.
func (*EditFeeProfileRequest) Descriptor() ([]byte, []int) {
	return file_fee_profiles_proto_rawDescGZIP(), []int{4}
}

func (x *EditFeeProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditFeeProfileRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EditFeeProfileRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *EditFeeProfileRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *EditFeeProfileRequest) GetSubTransactionTypeId() string {
	if x != nil {
		return x.SubTransactionTypeId
	}
	return ""
}

func (x *EditFeeProfileRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditFeeProfileRequest) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *EditFeeProfileRequest) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *EditFeeProfileRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *EditFeeProfileRequest) GetApprovedAt() string {
	if x != nil {
		return x.ApprovedAt
	}
	return ""
}

func (x *EditFeeProfileRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *EditFeeProfileRequest) GetRejectedReason() string {
	if x != nil {
		return x.RejectedReason
	}
	return ""
}

func (x *EditFeeProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditFeeProfileRequest) GetCalculationMode() string {
	if x != nil {
		return x.CalculationMode
	}
	return ""
}

var File_fee_profiles_proto protoreflect.FileDescriptor

const file_fee_profiles_proto_rawDesc = "" +
	"\n" +
	"\x12fee-profiles.proto\x12\x12fee_profiles_proto\"\xb5\x04\n" +
	"\x17CreateFeeProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x05 \x01(\tR\x14subTransactionTypeId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rcharge_amount\x18\a \x01(\tR\fchargeAmount\x12'\n" +
	"\x0fapproval_status\x18\b \x01(\tR\x0eapprovalStatus\x12\x1f\n" +
	"\vapproved_by\x18\t \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\n" +
	" \x01(\tR\n" +
	"approvedAt\x12\x1f\n" +
	"\vrejected_by\x18\v \x01(\tR\n" +
	"rejectedBy\x12'\n" +
	"\x0frejected_reason\x18\r \x01(\tR\x0erejectedReason\x12)\n" +
	"\x10calculation_mode\x18\x0e \x01(\tR\x0fcalculationMode\x12\x1f\n" +
	"\vcharge_type\x18\x0f \x01(\tR\n" +
	"chargeType\x12\x1f\n" +
	"\vminimum_fee\x18\x10 \x01(\tR\n" +
	"minimumFee\"\xd5\x05\n" +
	"\n" +
	"FeeProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x05 \x01(\tR\x14subTransactionTypeId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rcharge_amount\x18\a \x01(\tR\fchargeAmount\x12'\n" +
	"\x0fapproval_status\x18\b \x01(\tR\x0eapprovalStatus\x12\x1f\n" +
	"\vapproved_by\x18\t \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\n" +
	" \x01(\tR\n" +
	"approvedAt\x12\x1f\n" +
	"\vrejected_by\x18\v \x01(\tR\n" +
	"rejectedBy\x12'\n" +
	"\x0frejected_reason\x18\r \x01(\tR\x0erejectedReason\x12)\n" +
	"\x10calculation_mode\x18\x0e \x01(\tR\x0fcalculationMode\x12\x0e\n" +
	"\x02id\x18\x0f \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\tR\tupdatedAt\x120\n" +
	"\x14payment_channel_name\x18\x12 \x01(\tR\x12paymentChannelName\x122\n" +
	"\x15transaction_type_name\x18\x13 \x01(\tR\x13transactionTypeName\x129\n" +
	"\x19sub_transaction_type_name\x18\x14 \x01(\tR\x16subTransactionTypeName\"i\n" +
	"\x15GetFeeProfilesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12 \n" +
	"\vsearchQuery\x18\x03 \x01(\tR\vsearchQuery\"\xb5\x01\n" +
	"\x16GetFeeProfilesResponse\x12?\n" +
	"\vfee_profile\x18\x01 \x03(\v2\x1e.fee_profiles_proto.FeeProfileR\n" +
	"feeProfile\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"\x81\x04\n" +
	"\x15EditFeeProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\tR\x11transactionTypeId\x125\n" +
	"\x17sub_transaction_type_id\x18\x05 \x01(\tR\x14subTransactionTypeId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rcharge_amount\x18\a \x01(\tR\fchargeAmount\x12'\n" +
	"\x0fapproval_status\x18\b \x01(\tR\x0eapprovalStatus\x12\x1f\n" +
	"\vapproved_by\x18\t \x01(\tR\n" +
	"approvedBy\x12\x1f\n" +
	"\vapproved_at\x18\n" +
	" \x01(\tR\n" +
	"approvedAt\x12\x1f\n" +
	"\vrejected_by\x18\v \x01(\tR\n" +
	"rejectedBy\x12'\n" +
	"\x0frejected_reason\x18\f \x01(\tR\x0erejectedReason\x12\x0e\n" +
	"\x02id\x18\r \x01(\tR\x02id\x12)\n" +
	"\x10calculation_mode\x18\x0e \x01(\tR\x0fcalculationModeB.Z,/proto/fee_profiles_proto;fee_profiles_protob\x06proto3"

var (
	file_fee_profiles_proto_rawDescOnce sync.Once
	file_fee_profiles_proto_rawDescData []byte
)

func file_fee_profiles_proto_rawDescGZIP() []byte {
	file_fee_profiles_proto_rawDescOnce.Do(func() {
		file_fee_profiles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fee_profiles_proto_rawDesc), len(file_fee_profiles_proto_rawDesc)))
	})
	return file_fee_profiles_proto_rawDescData
}

var file_fee_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fee_profiles_proto_goTypes = []any{
	(*CreateFeeProfileRequest)(nil), // 0: fee_profiles_proto.CreateFeeProfileRequest
	(*FeeProfile)(nil),              // 1: fee_profiles_proto.FeeProfile
	(*GetFeeProfilesRequest)(nil),   // 2: fee_profiles_proto.GetFeeProfilesRequest
	(*GetFeeProfilesResponse)(nil),  // 3: fee_profiles_proto.GetFeeProfilesResponse
	(*EditFeeProfileRequest)(nil),   // 4: fee_profiles_proto.EditFeeProfileRequest
}
var file_fee_profiles_proto_depIdxs = []int32{
	1, // 0: fee_profiles_proto.GetFeeProfilesResponse.fee_profile:type_name -> fee_profiles_proto.FeeProfile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fee_profiles_proto_init() }
func file_fee_profiles_proto_init() {
	if File_fee_profiles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fee_profiles_proto_rawDesc), len(file_fee_profiles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fee_profiles_proto_goTypes,
		DependencyIndexes: file_fee_profiles_proto_depIdxs,
		MessageInfos:      file_fee_profiles_proto_msgTypes,
	}.Build()
	File_fee_profiles_proto = out.File
	file_fee_profiles_proto_goTypes = nil
	file_fee_profiles_proto_depIdxs = nil
}
