// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: merchant-api-keys.proto

package merchant_api_keys_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantAPIKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Pin           string                 `protobuf:"bytes,4,opt,name=pin,proto3" json:"pin,omitempty"`
	AuthSignature string                 `protobuf:"bytes,5,opt,name=auth_signature,json=authSignature,proto3" json:"auth_signature,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantAPIKey) Reset() {
	*x = MerchantAPIKey{}
	mi := &file_merchant_api_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAPIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAPIKey) ProtoMessage() {}

func (x *MerchantAPIKey) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_api_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAPIKey.ProtoReflect.Descriptor instead.
func (*MerchantAPIKey) Descriptor() ([]byte, []int) {
	return file_merchant_api_keys_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantAPIKey) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantAPIKey) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MerchantAPIKey) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *MerchantAPIKey) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *MerchantAPIKey) GetAuthSignature() string {
	if x != nil {
		return x.AuthSignature
	}
	return ""
}

func (x *MerchantAPIKey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantAPIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantAPIKey) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantAPIKey) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMerchantAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantAPIKeysRequest) Reset() {
	*x = GetMerchantAPIKeysRequest{}
	mi := &file_merchant_api_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantAPIKeysRequest) ProtoMessage() {}

func (x *GetMerchantAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_api_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_merchant_api_keys_proto_rawDescGZIP(), []int{1}
}

func (x *GetMerchantAPIKeysRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMerchantAPIKeysRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMerchantAPIKeysRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetMerchantAPIKeysRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantAPIKeysResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MerchantApiKeys []*MerchantAPIKey      `protobuf:"bytes,1,rep,name=merchant_api_keys,json=merchantApiKeys,proto3" json:"merchant_api_keys,omitempty"` // List of merchant API keys
	TotalPages      int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                 // Total number of pages
	CurrentPage     int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`              // Current page
	HasMore         bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                          // Whether there are more pages
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMerchantAPIKeysResponse) Reset() {
	*x = GetMerchantAPIKeysResponse{}
	mi := &file_merchant_api_keys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantAPIKeysResponse) ProtoMessage() {}

func (x *GetMerchantAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_api_keys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_merchant_api_keys_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantAPIKeysResponse) GetMerchantApiKeys() []*MerchantAPIKey {
	if x != nil {
		return x.MerchantApiKeys
	}
	return nil
}

func (x *GetMerchantAPIKeysResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetMerchantAPIKeysResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetMerchantAPIKeysResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditMerchantAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Pin           string                 `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	AuthSignature string                 `protobuf:"bytes,4,opt,name=auth_signature,json=authSignature,proto3" json:"auth_signature,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMerchantAPIKeyRequest) Reset() {
	*x = EditMerchantAPIKeyRequest{}
	mi := &file_merchant_api_keys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMerchantAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMerchantAPIKeyRequest) ProtoMessage() {}

func (x *EditMerchantAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_api_keys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMerchantAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*EditMerchantAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_merchant_api_keys_proto_rawDescGZIP(), []int{3}
}

func (x *EditMerchantAPIKeyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *EditMerchantAPIKeyRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *EditMerchantAPIKeyRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *EditMerchantAPIKeyRequest) GetAuthSignature() string {
	if x != nil {
		return x.AuthSignature
	}
	return ""
}

func (x *EditMerchantAPIKeyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditMerchantAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateAuthSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Pin           string                 `protobuf:"bytes,4,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAuthSignatureRequest) Reset() {
	*x = GenerateAuthSignatureRequest{}
	mi := &file_merchant_api_keys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAuthSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAuthSignatureRequest) ProtoMessage() {}

func (x *GenerateAuthSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_api_keys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAuthSignatureRequest.ProtoReflect.Descriptor instead.
func (*GenerateAuthSignatureRequest) Descriptor() ([]byte, []int) {
	return file_merchant_api_keys_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateAuthSignatureRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GenerateAuthSignatureRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GenerateAuthSignatureRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *GenerateAuthSignatureRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

var File_merchant_api_keys_proto protoreflect.FileDescriptor

const file_merchant_api_keys_proto_rawDesc = "" +
	"\n" +
	"\x17merchant-api-keys.proto\x12\x17merchant_api_keys_proto\"\x92\x02\n" +
	"\x0eMerchantAPIKey\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x10\n" +
	"\x03pin\x18\x04 \x01(\tR\x03pin\x12%\n" +
	"\x0eauth_signature\x18\x05 \x01(\tR\rauthSignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x90\x01\n" +
	"\x19GetMerchantAPIKeysRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\"\xd0\x01\n" +
	"\x1aGetMerchantAPIKeysResponse\x12S\n" +
	"\x11merchant_api_keys\x18\x01 \x03(\v2'.merchant_api_keys_proto.MerchantAPIKeyR\x0fmerchantApiKeys\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xbe\x01\n" +
	"\x19EditMerchantAPIKeyRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\tR\x03pin\x12%\n" +
	"\x0eauth_signature\x18\x04 \x01(\tR\rauthSignature\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\x93\x01\n" +
	"\x1cGenerateAuthSignatureRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x12\x10\n" +
	"\x03pin\x18\x04 \x01(\tR\x03pinB8Z6/proto/merchant_api_keys_proto;merchant_api_keys_protob\x06proto3"

var (
	file_merchant_api_keys_proto_rawDescOnce sync.Once
	file_merchant_api_keys_proto_rawDescData []byte
)

func file_merchant_api_keys_proto_rawDescGZIP() []byte {
	file_merchant_api_keys_proto_rawDescOnce.Do(func() {
		file_merchant_api_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_api_keys_proto_rawDesc), len(file_merchant_api_keys_proto_rawDesc)))
	})
	return file_merchant_api_keys_proto_rawDescData
}

var file_merchant_api_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_merchant_api_keys_proto_goTypes = []any{
	(*MerchantAPIKey)(nil),               // 0: merchant_api_keys_proto.MerchantAPIKey
	(*GetMerchantAPIKeysRequest)(nil),    // 1: merchant_api_keys_proto.GetMerchantAPIKeysRequest
	(*GetMerchantAPIKeysResponse)(nil),   // 2: merchant_api_keys_proto.GetMerchantAPIKeysResponse
	(*EditMerchantAPIKeyRequest)(nil),    // 3: merchant_api_keys_proto.EditMerchantAPIKeyRequest
	(*GenerateAuthSignatureRequest)(nil), // 4: merchant_api_keys_proto.GenerateAuthSignatureRequest
}
var file_merchant_api_keys_proto_depIdxs = []int32{
	0, // 0: merchant_api_keys_proto.GetMerchantAPIKeysResponse.merchant_api_keys:type_name -> merchant_api_keys_proto.MerchantAPIKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_api_keys_proto_init() }
func file_merchant_api_keys_proto_init() {
	if File_merchant_api_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_api_keys_proto_rawDesc), len(file_merchant_api_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merchant_api_keys_proto_goTypes,
		DependencyIndexes: file_merchant_api_keys_proto_depIdxs,
		MessageInfos:      file_merchant_api_keys_proto_msgTypes,
	}.Build()
	File_merchant_api_keys_proto = out.File
	file_merchant_api_keys_proto_goTypes = nil
	file_merchant_api_keys_proto_depIdxs = nil
}
