// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: merchant-fee-profile.proto

package merchant_fee_profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMerchantFeeProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	FeeProfileId  string                 `protobuf:"bytes,2,opt,name=fee_profile_id,json=feeProfileId,proto3" json:"fee_profile_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantFeeProfileRequest) Reset() {
	*x = CreateMerchantFeeProfileRequest{}
	mi := &file_merchant_fee_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantFeeProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantFeeProfileRequest) ProtoMessage() {}

func (x *CreateMerchantFeeProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_fee_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantFeeProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantFeeProfileRequest) Descriptor() ([]byte, []int) {
	return file_merchant_fee_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMerchantFeeProfileRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateMerchantFeeProfileRequest) GetFeeProfileId() string {
	if x != nil {
		return x.FeeProfileId
	}
	return ""
}

func (x *CreateMerchantFeeProfileRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MerchantFeeProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	FeeProfileId  string                 `protobuf:"bytes,2,opt,name=fee_profile_id,json=feeProfileId,proto3" json:"fee_profile_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantFeeProfile) Reset() {
	*x = MerchantFeeProfile{}
	mi := &file_merchant_fee_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantFeeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantFeeProfile) ProtoMessage() {}

func (x *MerchantFeeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_fee_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantFeeProfile.ProtoReflect.Descriptor instead.
func (*MerchantFeeProfile) Descriptor() ([]byte, []int) {
	return file_merchant_fee_profile_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantFeeProfile) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantFeeProfile) GetFeeProfileId() string {
	if x != nil {
		return x.FeeProfileId
	}
	return ""
}

func (x *MerchantFeeProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantFeeProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantFeeProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantFeeProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMerchantFeeProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantFeeProfilesRequest) Reset() {
	*x = GetMerchantFeeProfilesRequest{}
	mi := &file_merchant_fee_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantFeeProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantFeeProfilesRequest) ProtoMessage() {}

func (x *GetMerchantFeeProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_fee_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantFeeProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantFeeProfilesRequest) Descriptor() ([]byte, []int) {
	return file_merchant_fee_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantFeeProfilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMerchantFeeProfilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMerchantFeeProfilesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetMerchantFeeProfilesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MerchantFeeProfile []*MerchantFeeProfile  `protobuf:"bytes,1,rep,name=merchant_fee_profile,json=merchantFeeProfile,proto3" json:"merchant_fee_profile,omitempty"` // List of merchant fee profiles
	TotalPages         int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                          // Total number of pages
	CurrentPage        int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`                       // Current page
	HasMore            bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                                   // Whether there are more pages
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetMerchantFeeProfilesResponse) Reset() {
	*x = GetMerchantFeeProfilesResponse{}
	mi := &file_merchant_fee_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantFeeProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantFeeProfilesResponse) ProtoMessage() {}

func (x *GetMerchantFeeProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_fee_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantFeeProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantFeeProfilesResponse) Descriptor() ([]byte, []int) {
	return file_merchant_fee_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantFeeProfilesResponse) GetMerchantFeeProfile() []*MerchantFeeProfile {
	if x != nil {
		return x.MerchantFeeProfile
	}
	return nil
}

func (x *GetMerchantFeeProfilesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetMerchantFeeProfilesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetMerchantFeeProfilesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditMerchantFeeProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	FeeProfileId  string                 `protobuf:"bytes,2,opt,name=fee_profile_id,json=feeProfileId,proto3" json:"fee_profile_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMerchantFeeProfileRequest) Reset() {
	*x = EditMerchantFeeProfileRequest{}
	mi := &file_merchant_fee_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMerchantFeeProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMerchantFeeProfileRequest) ProtoMessage() {}

func (x *EditMerchantFeeProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_fee_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMerchantFeeProfileRequest.ProtoReflect.Descriptor instead.
func (*EditMerchantFeeProfileRequest) Descriptor() ([]byte, []int) {
	return file_merchant_fee_profile_proto_rawDescGZIP(), []int{4}
}

func (x *EditMerchantFeeProfileRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *EditMerchantFeeProfileRequest) GetFeeProfileId() string {
	if x != nil {
		return x.FeeProfileId
	}
	return ""
}

func (x *EditMerchantFeeProfileRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditMerchantFeeProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_merchant_fee_profile_proto protoreflect.FileDescriptor

const file_merchant_fee_profile_proto_rawDesc = "" +
	"\n" +
	"\x1amerchant-fee-profile.proto\x12\x14merchant_fee_profile\"\x80\x01\n" +
	"\x1fCreateMerchantFeeProfileRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12$\n" +
	"\x0efee_profile_id\x18\x02 \x01(\tR\ffeeProfileId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xc1\x01\n" +
	"\x12MerchantFeeProfile\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12$\n" +
	"\x0efee_profile_id\x18\x02 \x01(\tR\ffeeProfileId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"s\n" +
	"\x1dGetMerchantFeeProfilesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xdb\x01\n" +
	"\x1eGetMerchantFeeProfilesResponse\x12Z\n" +
	"\x14merchant_fee_profile\x18\x01 \x03(\v2(.merchant_fee_profile.MerchantFeeProfileR\x12merchantFeeProfile\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x8e\x01\n" +
	"\x1dEditMerchantFeeProfileRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12$\n" +
	"\x0efee_profile_id\x18\x02 \x01(\tR\ffeeProfileId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02idB2Z0/proto/merchant_fee_profile;merchant_fee_profileb\x06proto3"

var (
	file_merchant_fee_profile_proto_rawDescOnce sync.Once
	file_merchant_fee_profile_proto_rawDescData []byte
)

func file_merchant_fee_profile_proto_rawDescGZIP() []byte {
	file_merchant_fee_profile_proto_rawDescOnce.Do(func() {
		file_merchant_fee_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_fee_profile_proto_rawDesc), len(file_merchant_fee_profile_proto_rawDesc)))
	})
	return file_merchant_fee_profile_proto_rawDescData
}

var file_merchant_fee_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_merchant_fee_profile_proto_goTypes = []any{
	(*CreateMerchantFeeProfileRequest)(nil), // 0: merchant_fee_profile.CreateMerchantFeeProfileRequest
	(*MerchantFeeProfile)(nil),              // 1: merchant_fee_profile.MerchantFeeProfile
	(*GetMerchantFeeProfilesRequest)(nil),   // 2: merchant_fee_profile.GetMerchantFeeProfilesRequest
	(*GetMerchantFeeProfilesResponse)(nil),  // 3: merchant_fee_profile.GetMerchantFeeProfilesResponse
	(*EditMerchantFeeProfileRequest)(nil),   // 4: merchant_fee_profile.EditMerchantFeeProfileRequest
}
var file_merchant_fee_profile_proto_depIdxs = []int32{
	1, // 0: merchant_fee_profile.GetMerchantFeeProfilesResponse.merchant_fee_profile:type_name -> merchant_fee_profile.MerchantFeeProfile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_fee_profile_proto_init() }
func file_merchant_fee_profile_proto_init() {
	if File_merchant_fee_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_fee_profile_proto_rawDesc), len(file_merchant_fee_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merchant_fee_profile_proto_goTypes,
		DependencyIndexes: file_merchant_fee_profile_proto_depIdxs,
		MessageInfos:      file_merchant_fee_profile_proto_msgTypes,
	}.Build()
	File_merchant_fee_profile_proto = out.File
	file_merchant_fee_profile_proto_goTypes = nil
	file_merchant_fee_profile_proto_depIdxs = nil
}
