// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: profile-fee-bands.proto

package profile_fee_bands

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProfileFeeBandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeProfileId  string                 `protobuf:"bytes,1,opt,name=fee_profile_id,json=feeProfileId,proto3" json:"fee_profile_id,omitempty"`
	MinAmount     string                 `protobuf:"bytes,2,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ChargeAmount  string                 `protobuf:"bytes,4,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	ChargeType    string                 `protobuf:"bytes,5,opt,name=charge_type,json=chargeType,proto3" json:"charge_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileFeeBandsRequest) Reset() {
	*x = CreateProfileFeeBandsRequest{}
	mi := &file_profile_fee_bands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileFeeBandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileFeeBandsRequest) ProtoMessage() {}

func (x *CreateProfileFeeBandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_fee_bands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileFeeBandsRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileFeeBandsRequest) Descriptor() ([]byte, []int) {
	return file_profile_fee_bands_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileFeeBandsRequest) GetFeeProfileId() string {
	if x != nil {
		return x.FeeProfileId
	}
	return ""
}

func (x *CreateProfileFeeBandsRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *CreateProfileFeeBandsRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *CreateProfileFeeBandsRequest) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *CreateProfileFeeBandsRequest) GetChargeType() string {
	if x != nil {
		return x.ChargeType
	}
	return ""
}

func (x *CreateProfileFeeBandsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProfileFeeBands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeProfileId  string                 `protobuf:"bytes,1,opt,name=fee_profile_id,json=feeProfileId,proto3" json:"fee_profile_id,omitempty"`
	MinAmount     string                 `protobuf:"bytes,2,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ChargeAmount  string                 `protobuf:"bytes,4,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	ChargeType    string                 `protobuf:"bytes,5,opt,name=charge_type,json=chargeType,proto3" json:"charge_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileFeeBands) Reset() {
	*x = ProfileFeeBands{}
	mi := &file_profile_fee_bands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileFeeBands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileFeeBands) ProtoMessage() {}

func (x *ProfileFeeBands) ProtoReflect() protoreflect.Message {
	mi := &file_profile_fee_bands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileFeeBands.ProtoReflect.Descriptor instead.
func (*ProfileFeeBands) Descriptor() ([]byte, []int) {
	return file_profile_fee_bands_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileFeeBands) GetFeeProfileId() string {
	if x != nil {
		return x.FeeProfileId
	}
	return ""
}

func (x *ProfileFeeBands) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *ProfileFeeBands) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *ProfileFeeBands) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *ProfileFeeBands) GetChargeType() string {
	if x != nil {
		return x.ChargeType
	}
	return ""
}

func (x *ProfileFeeBands) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProfileFeeBands) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileFeeBands) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProfileFeeBands) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetProfileFeeBandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileFeeBandsRequest) Reset() {
	*x = GetProfileFeeBandsRequest{}
	mi := &file_profile_fee_bands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileFeeBandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileFeeBandsRequest) ProtoMessage() {}

func (x *GetProfileFeeBandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_fee_bands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileFeeBandsRequest.ProtoReflect.Descriptor instead.
func (*GetProfileFeeBandsRequest) Descriptor() ([]byte, []int) {
	return file_profile_fee_bands_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileFeeBandsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProfileFeeBandsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetProfileFeeBandsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetProfileFeeBandsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProfileFeeBands []*ProfileFeeBands     `protobuf:"bytes,1,rep,name=profile_fee_bands,json=profileFeeBands,proto3" json:"profile_fee_bands,omitempty"` // List of profile fee bands
	TotalPages      int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                 // Total number of pages
	CurrentPage     int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`              // Current page
	HasMore         bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                          // Whether there are more pages
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProfileFeeBandsResponse) Reset() {
	*x = GetProfileFeeBandsResponse{}
	mi := &file_profile_fee_bands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileFeeBandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileFeeBandsResponse) ProtoMessage() {}

func (x *GetProfileFeeBandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_fee_bands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileFeeBandsResponse.ProtoReflect.Descriptor instead.
func (*GetProfileFeeBandsResponse) Descriptor() ([]byte, []int) {
	return file_profile_fee_bands_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileFeeBandsResponse) GetProfileFeeBands() []*ProfileFeeBands {
	if x != nil {
		return x.ProfileFeeBands
	}
	return nil
}

func (x *GetProfileFeeBandsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetProfileFeeBandsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetProfileFeeBandsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditProfileFeeBandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FeeProfileId  string                 `protobuf:"bytes,2,opt,name=fee_profile_id,json=feeProfileId,proto3" json:"fee_profile_id,omitempty"`
	MinAmount     string                 `protobuf:"bytes,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,4,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	ChargeAmount  string                 `protobuf:"bytes,5,opt,name=charge_amount,json=chargeAmount,proto3" json:"charge_amount,omitempty"`
	ChargeType    string                 `protobuf:"bytes,6,opt,name=charge_type,json=chargeType,proto3" json:"charge_type,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditProfileFeeBandsRequest) Reset() {
	*x = EditProfileFeeBandsRequest{}
	mi := &file_profile_fee_bands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditProfileFeeBandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditProfileFeeBandsRequest) ProtoMessage() {}

func (x *EditProfileFeeBandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_fee_bands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditProfileFeeBandsRequest.ProtoReflect.Descriptor instead.
func (*EditProfileFeeBandsRequest) Descriptor() ([]byte, []int) {
	return file_profile_fee_bands_proto_rawDescGZIP(), []int{4}
}

func (x *EditProfileFeeBandsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetFeeProfileId() string {
	if x != nil {
		return x.FeeProfileId
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetChargeAmount() string {
	if x != nil {
		return x.ChargeAmount
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetChargeType() string {
	if x != nil {
		return x.ChargeType
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditProfileFeeBandsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_profile_fee_bands_proto protoreflect.FileDescriptor

const file_profile_fee_bands_proto_rawDesc = "" +
	"\n" +
	"\x17profile-fee-bands.proto\x12\x11profile_fee_bands\"\xe0\x01\n" +
	"\x1cCreateProfileFeeBandsRequest\x12$\n" +
	"\x0efee_profile_id\x18\x01 \x01(\tR\ffeeProfileId\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x02 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12#\n" +
	"\rcharge_amount\x18\x04 \x01(\tR\fchargeAmount\x12\x1f\n" +
	"\vcharge_type\x18\x05 \x01(\tR\n" +
	"chargeType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xa1\x02\n" +
	"\x0fProfileFeeBands\x12$\n" +
	"\x0efee_profile_id\x18\x01 \x01(\tR\ffeeProfileId\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x02 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12#\n" +
	"\rcharge_amount\x18\x04 \x01(\tR\fchargeAmount\x12\x1f\n" +
	"\vcharge_type\x18\x05 \x01(\tR\n" +
	"chargeType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"o\n" +
	"\x19GetProfileFeeBandsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xcb\x01\n" +
	"\x1aGetProfileFeeBandsResponse\x12N\n" +
	"\x11profile_fee_bands\x18\x01 \x03(\v2\".profile_fee_bands.ProfileFeeBandsR\x0fprofileFeeBands\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x82\x02\n" +
	"\x1aEditProfileFeeBandsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x0efee_profile_id\x18\x02 \x01(\tR\ffeeProfileId\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x03 \x01(\tR\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x04 \x01(\tR\tmaxAmount\x12#\n" +
	"\rcharge_amount\x18\x05 \x01(\tR\fchargeAmount\x12\x1f\n" +
	"\vcharge_type\x18\x06 \x01(\tR\n" +
	"chargeType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02idB,Z*/proto/profile_fee_bands;profile_fee_bandsb\x06proto3"

var (
	file_profile_fee_bands_proto_rawDescOnce sync.Once
	file_profile_fee_bands_proto_rawDescData []byte
)

func file_profile_fee_bands_proto_rawDescGZIP() []byte {
	file_profile_fee_bands_proto_rawDescOnce.Do(func() {
		file_profile_fee_bands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_fee_bands_proto_rawDesc), len(file_profile_fee_bands_proto_rawDesc)))
	})
	return file_profile_fee_bands_proto_rawDescData
}

var file_profile_fee_bands_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profile_fee_bands_proto_goTypes = []any{
	(*CreateProfileFeeBandsRequest)(nil), // 0: profile_fee_bands.CreateProfileFeeBandsRequest
	(*ProfileFeeBands)(nil),              // 1: profile_fee_bands.ProfileFeeBands
	(*GetProfileFeeBandsRequest)(nil),    // 2: profile_fee_bands.GetProfileFeeBandsRequest
	(*GetProfileFeeBandsResponse)(nil),   // 3: profile_fee_bands.GetProfileFeeBandsResponse
	(*EditProfileFeeBandsRequest)(nil),   // 4: profile_fee_bands.EditProfileFeeBandsRequest
}
var file_profile_fee_bands_proto_depIdxs = []int32{
	1, // 0: profile_fee_bands.GetProfileFeeBandsResponse.profile_fee_bands:type_name -> profile_fee_bands.ProfileFeeBands
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profile_fee_bands_proto_init() }
func file_profile_fee_bands_proto_init() {
	if File_profile_fee_bands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_fee_bands_proto_rawDesc), len(file_profile_fee_bands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_fee_bands_proto_goTypes,
		DependencyIndexes: file_profile_fee_bands_proto_depIdxs,
		MessageInfos:      file_profile_fee_bands_proto_msgTypes,
	}.Build()
	File_profile_fee_bands_proto = out.File
	file_profile_fee_bands_proto_goTypes = nil
	file_profile_fee_bands_proto_depIdxs = nil
}
