// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: transaction-types.proto

package transaction_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	MinAmount     string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionTypeRequest) Reset() {
	*x = CreateTransactionTypeRequest{}
	mi := &file_transaction_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionTypeRequest) ProtoMessage() {}

func (x *CreateTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTransactionTypeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateTransactionTypeRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *CreateTransactionTypeRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *CreateTransactionTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TransactionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	MinAmount     string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionType) Reset() {
	*x = TransactionType{}
	mi := &file_transaction_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionType) ProtoMessage() {}

func (x *TransactionType) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionType.ProtoReflect.Descriptor instead.
func (*TransactionType) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransactionType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TransactionType) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *TransactionType) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *TransactionType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionType) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionType) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetTransactionTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionTypesRequest) Reset() {
	*x = GetTransactionTypesRequest{}
	mi := &file_transaction_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionTypesRequest) ProtoMessage() {}

func (x *GetTransactionTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionTypesRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionTypesRequest) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionTypesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransactionTypesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetTransactionTypesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionType []*TransactionType     `protobuf:"bytes,1,rep,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // List of transaction types
	TotalPages      int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`               // Total number of pages
	CurrentPage     int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`            // Current page
	HasMore         bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                        // Whether there are more pages
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionTypesResponse) Reset() {
	*x = GetTransactionTypesResponse{}
	mi := &file_transaction_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionTypesResponse) ProtoMessage() {}

func (x *GetTransactionTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionTypesResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionTypesResponse) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionTypesResponse) GetTransactionType() []*TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *GetTransactionTypesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetTransactionTypesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetTransactionTypesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditTransactionTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	MaxAmount     string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	MinAmount     string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTransactionTypeRequest) Reset() {
	*x = EditTransactionTypeRequest{}
	mi := &file_transaction_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTransactionTypeRequest) ProtoMessage() {}

func (x *EditTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*EditTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{4}
}

func (x *EditTransactionTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditTransactionTypeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EditTransactionTypeRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *EditTransactionTypeRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *EditTransactionTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditTransactionTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSubTransactionTypeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	MaxAmount         string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	MinAmount         string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransactionTypeId string                 `protobuf:"bytes,6,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateSubTransactionTypeRequest) Reset() {
	*x = CreateSubTransactionTypeRequest{}
	mi := &file_transaction_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubTransactionTypeRequest) ProtoMessage() {}

func (x *CreateSubTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateSubTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubTransactionTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubTransactionTypeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateSubTransactionTypeRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *CreateSubTransactionTypeRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *CreateSubTransactionTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSubTransactionTypeRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

type SubTransactionType struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	MaxAmount         string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	MinAmount         string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransactionTypeId string                 `protobuf:"bytes,6,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Id                string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubTransactionType) Reset() {
	*x = SubTransactionType{}
	mi := &file_transaction_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubTransactionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubTransactionType) ProtoMessage() {}

func (x *SubTransactionType) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubTransactionType.ProtoReflect.Descriptor instead.
func (*SubTransactionType) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{6}
}

func (x *SubTransactionType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubTransactionType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubTransactionType) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *SubTransactionType) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *SubTransactionType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubTransactionType) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *SubTransactionType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubTransactionType) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SubTransactionType) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSubTransactionTypesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Page              int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize          int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery       string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	TransactionTypeId string                 `protobuf:"bytes,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSubTransactionTypesRequest) Reset() {
	*x = GetSubTransactionTypesRequest{}
	mi := &file_transaction_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubTransactionTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubTransactionTypesRequest) ProtoMessage() {}

func (x *GetSubTransactionTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubTransactionTypesRequest.ProtoReflect.Descriptor instead.
func (*GetSubTransactionTypesRequest) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{7}
}

func (x *GetSubTransactionTypesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubTransactionTypesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSubTransactionTypesRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetSubTransactionTypesRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

type GetSubTransactionTypesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubTransactionType []*SubTransactionType  `protobuf:"bytes,1,rep,name=sub_transaction_type,json=subTransactionType,proto3" json:"sub_transaction_type,omitempty"` // List of sub transaction types
	TotalPages         int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                          // Total number of pages
	CurrentPage        int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`                       // Current page
	HasMore            bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                                   // Whether there are more pages
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSubTransactionTypesResponse) Reset() {
	*x = GetSubTransactionTypesResponse{}
	mi := &file_transaction_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubTransactionTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubTransactionTypesResponse) ProtoMessage() {}

func (x *GetSubTransactionTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubTransactionTypesResponse.ProtoReflect.Descriptor instead.
func (*GetSubTransactionTypesResponse) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubTransactionTypesResponse) GetSubTransactionType() []*SubTransactionType {
	if x != nil {
		return x.SubTransactionType
	}
	return nil
}

func (x *GetSubTransactionTypesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetSubTransactionTypesResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetSubTransactionTypesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditSubTransactionTypeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code              string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	MaxAmount         string                 `protobuf:"bytes,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	MinAmount         string                 `protobuf:"bytes,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	Status            string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TransactionTypeId string                 `protobuf:"bytes,6,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Id                string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EditSubTransactionTypeRequest) Reset() {
	*x = EditSubTransactionTypeRequest{}
	mi := &file_transaction_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSubTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSubTransactionTypeRequest) ProtoMessage() {}

func (x *EditSubTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSubTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*EditSubTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_types_proto_rawDescGZIP(), []int{9}
}

func (x *EditSubTransactionTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditSubTransactionTypeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EditSubTransactionTypeRequest) GetMaxAmount() string {
	if x != nil {
		return x.MaxAmount
	}
	return ""
}

func (x *EditSubTransactionTypeRequest) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

func (x *EditSubTransactionTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditSubTransactionTypeRequest) GetTransactionTypeId() string {
	if x != nil {
		return x.TransactionTypeId
	}
	return ""
}

func (x *EditSubTransactionTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_transaction_types_proto protoreflect.FileDescriptor

const file_transaction_types_proto_rawDesc = "" +
	"\n" +
	"\x17transaction-types.proto\x12\x11transaction_types\"\x9c\x01\n" +
	"\x1cCreateTransactionTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xdd\x01\n" +
	"\x0fTransactionType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"p\n" +
	"\x1aGetTransactionTypesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xcb\x01\n" +
	"\x1bGetTransactionTypesResponse\x12M\n" +
	"\x10transaction_type\x18\x01 \x03(\v2\".transaction_types.TransactionTypeR\x0ftransactionType\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xaa\x01\n" +
	"\x1aEditTransactionTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\xcf\x01\n" +
	"\x1fCreateSubTransactionTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12.\n" +
	"\x13transaction_type_id\x18\x06 \x01(\tR\x11transactionTypeId\"\x90\x02\n" +
	"\x12SubTransactionType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12.\n" +
	"\x13transaction_type_id\x18\x06 \x01(\tR\x11transactionTypeId\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xa3\x01\n" +
	"\x1dGetSubTransactionTypesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\tR\x11transactionTypeId\"\xd8\x01\n" +
	"\x1eGetSubTransactionTypesResponse\x12W\n" +
	"\x14sub_transaction_type\x18\x01 \x03(\v2%.transaction_types.SubTransactionTypeR\x12subTransactionType\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xdd\x01\n" +
	"\x1dEditSubTransactionTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\tR\tmaxAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\tR\tminAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12.\n" +
	"\x13transaction_type_id\x18\x06 \x01(\tR\x11transactionTypeId\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02idB,Z*/proto/transaction_types;transaction_typesb\x06proto3"

var (
	file_transaction_types_proto_rawDescOnce sync.Once
	file_transaction_types_proto_rawDescData []byte
)

func file_transaction_types_proto_rawDescGZIP() []byte {
	file_transaction_types_proto_rawDescOnce.Do(func() {
		file_transaction_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_types_proto_rawDesc), len(file_transaction_types_proto_rawDesc)))
	})
	return file_transaction_types_proto_rawDescData
}

var file_transaction_types_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_transaction_types_proto_goTypes = []any{
	(*CreateTransactionTypeRequest)(nil),    // 0: transaction_types.CreateTransactionTypeRequest
	(*TransactionType)(nil),                 // 1: transaction_types.TransactionType
	(*GetTransactionTypesRequest)(nil),      // 2: transaction_types.GetTransactionTypesRequest
	(*GetTransactionTypesResponse)(nil),     // 3: transaction_types.GetTransactionTypesResponse
	(*EditTransactionTypeRequest)(nil),      // 4: transaction_types.EditTransactionTypeRequest
	(*CreateSubTransactionTypeRequest)(nil), // 5: transaction_types.CreateSubTransactionTypeRequest
	(*SubTransactionType)(nil),              // 6: transaction_types.SubTransactionType
	(*GetSubTransactionTypesRequest)(nil),   // 7: transaction_types.GetSubTransactionTypesRequest
	(*GetSubTransactionTypesResponse)(nil),  // 8: transaction_types.GetSubTransactionTypesResponse
	(*EditSubTransactionTypeRequest)(nil),   // 9: transaction_types.EditSubTransactionTypeRequest
}
var file_transaction_types_proto_depIdxs = []int32{
	1, // 0: transaction_types.GetTransactionTypesResponse.transaction_type:type_name -> transaction_types.TransactionType
	6, // 1: transaction_types.GetSubTransactionTypesResponse.sub_transaction_type:type_name -> transaction_types.SubTransactionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_types_proto_init() }
func file_transaction_types_proto_init() {
	if File_transaction_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_types_proto_rawDesc), len(file_transaction_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_types_proto_goTypes,
		DependencyIndexes: file_transaction_types_proto_depIdxs,
		MessageInfos:      file_transaction_types_proto_msgTypes,
	}.Build()
	File_transaction_types_proto = out.File
	file_transaction_types_proto_goTypes = nil
	file_transaction_types_proto_depIdxs = nil
}
