// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: merchant-payment-channels.proto

package merchant_payment_channels_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMerchantPaymentChannelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	RejectionReason  string                 `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	AssignedBy       string                 `protobuf:"bytes,6,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	ApprovedBy       string                 `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMerchantPaymentChannelRequest) Reset() {
	*x = CreateMerchantPaymentChannelRequest{}
	mi := &file_merchant_payment_channels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantPaymentChannelRequest) ProtoMessage() {}

func (x *CreateMerchantPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMerchantPaymentChannelRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateMerchantPaymentChannelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateMerchantPaymentChannelRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *CreateMerchantPaymentChannelRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *CreateMerchantPaymentChannelRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *CreateMerchantPaymentChannelRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type MerchantPaymentChannel struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MerchantId         string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaymentChannelId   string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	RejectionReason    string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	AssignedBy         string                 `protobuf:"bytes,6,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	ApprovedBy         string                 `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	Id                 string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PaymentChannelName string                 `protobuf:"bytes,12,opt,name=payment_channel_name,json=paymentChannelName,proto3" json:"payment_channel_name,omitempty"`
	MerchantName       string                 `protobuf:"bytes,13,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	ApprovalStatus     string                 `protobuf:"bytes,14,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MerchantPaymentChannel) Reset() {
	*x = MerchantPaymentChannel{}
	mi := &file_merchant_payment_channels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantPaymentChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantPaymentChannel) ProtoMessage() {}

func (x *MerchantPaymentChannel) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantPaymentChannel.ProtoReflect.Descriptor instead.
func (*MerchantPaymentChannel) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantPaymentChannel) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantPaymentChannel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantPaymentChannel) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *MerchantPaymentChannel) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *MerchantPaymentChannel) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *MerchantPaymentChannel) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *MerchantPaymentChannel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantPaymentChannel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantPaymentChannel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantPaymentChannel) GetPaymentChannelName() string {
	if x != nil {
		return x.PaymentChannelName
	}
	return ""
}

func (x *MerchantPaymentChannel) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *MerchantPaymentChannel) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

type GetMerchantPaymentChannelsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Page             int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery      string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	MerchantId       string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,5,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RejectionReason  string                 `protobuf:"bytes,7,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	AssignedBy       string                 `protobuf:"bytes,8,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	ApprovedBy       string                 `protobuf:"bytes,9,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMerchantPaymentChannelsRequest) Reset() {
	*x = GetMerchantPaymentChannelsRequest{}
	mi := &file_merchant_payment_channels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantPaymentChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantPaymentChannelsRequest) ProtoMessage() {}

func (x *GetMerchantPaymentChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantPaymentChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantPaymentChannelsRequest) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantPaymentChannelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMerchantPaymentChannelsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMerchantPaymentChannelsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetMerchantPaymentChannelsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetMerchantPaymentChannelsRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *GetMerchantPaymentChannelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMerchantPaymentChannelsRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *GetMerchantPaymentChannelsRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *GetMerchantPaymentChannelsRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type GetMerchantPaymentChannelsResponse struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	MerchantPaymentChannels []*MerchantPaymentChannel `protobuf:"bytes,1,rep,name=merchant_payment_channels,json=merchantPaymentChannels,proto3" json:"merchant_payment_channels,omitempty"` // List of merchant payment channels
	TotalPages              int32                     `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                                         // Total number of pages
	CurrentPage             int32                     `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`                                      // Current page
	HasMore                 bool                      `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                                                  // Whether there are more pages
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetMerchantPaymentChannelsResponse) Reset() {
	*x = GetMerchantPaymentChannelsResponse{}
	mi := &file_merchant_payment_channels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantPaymentChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantPaymentChannelsResponse) ProtoMessage() {}

func (x *GetMerchantPaymentChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantPaymentChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantPaymentChannelsResponse) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantPaymentChannelsResponse) GetMerchantPaymentChannels() []*MerchantPaymentChannel {
	if x != nil {
		return x.MerchantPaymentChannels
	}
	return nil
}

func (x *GetMerchantPaymentChannelsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetMerchantPaymentChannelsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetMerchantPaymentChannelsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditMerchantPaymentChannelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantId       string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PaymentChannelId string                 `protobuf:"bytes,3,opt,name=payment_channel_id,json=paymentChannelId,proto3" json:"payment_channel_id,omitempty"`
	ApprovalStatus   string                 `protobuf:"bytes,4,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	RejectionReason  string                 `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	AssignedBy       string                 `protobuf:"bytes,6,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	ApprovedBy       string                 `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	Id               string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditMerchantPaymentChannelRequest) Reset() {
	*x = EditMerchantPaymentChannelRequest{}
	mi := &file_merchant_payment_channels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMerchantPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMerchantPaymentChannelRequest) ProtoMessage() {}

func (x *EditMerchantPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMerchantPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*EditMerchantPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{4}
}

func (x *EditMerchantPaymentChannelRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetPaymentChannelId() string {
	if x != nil {
		return x.PaymentChannelId
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *EditMerchantPaymentChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApproveMerchantPaymentChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveMerchantPaymentChannelRequest) Reset() {
	*x = ApproveMerchantPaymentChannelRequest{}
	mi := &file_merchant_payment_channels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveMerchantPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveMerchantPaymentChannelRequest) ProtoMessage() {}

func (x *ApproveMerchantPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveMerchantPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*ApproveMerchantPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveMerchantPaymentChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApproveMerchantPaymentChannelRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type RejectMerchantPaymentChannelRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RejectedBy      string                 `protobuf:"bytes,2,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	RejectionReason string                 `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RejectMerchantPaymentChannelRequest) Reset() {
	*x = RejectMerchantPaymentChannelRequest{}
	mi := &file_merchant_payment_channels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectMerchantPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectMerchantPaymentChannelRequest) ProtoMessage() {}

func (x *RejectMerchantPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_payment_channels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectMerchantPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*RejectMerchantPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_merchant_payment_channels_proto_rawDescGZIP(), []int{6}
}

func (x *RejectMerchantPaymentChannelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RejectMerchantPaymentChannelRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *RejectMerchantPaymentChannelRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

var File_merchant_payment_channels_proto protoreflect.FileDescriptor

const file_merchant_payment_channels_proto_rawDesc = "" +
	"\n" +
	"\x1fmerchant-payment-channels.proto\x12\x1fmerchant_payment_channels_proto\"\xf9\x01\n" +
	"#CreateMerchantPaymentChannelRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vassigned_by\x18\x06 \x01(\tR\n" +
	"assignedBy\x12\x1f\n" +
	"\vapproved_by\x18\a \x01(\tR\n" +
	"approvedBy\"\xba\x03\n" +
	"\x16MerchantPaymentChannel\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vassigned_by\x18\x06 \x01(\tR\n" +
	"assignedBy\x12\x1f\n" +
	"\vapproved_by\x18\a \x01(\tR\n" +
	"approvedBy\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x120\n" +
	"\x14payment_channel_name\x18\f \x01(\tR\x12paymentChannelName\x12#\n" +
	"\rmerchant_name\x18\r \x01(\tR\fmerchantName\x12'\n" +
	"\x0fapproval_status\x18\x0e \x01(\tR\x0eapprovalStatus\"\xcb\x02\n" +
	"!GetMerchantPaymentChannelsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12,\n" +
	"\x12payment_channel_id\x18\x05 \x01(\tR\x10paymentChannelId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x10rejection_reason\x18\a \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vassigned_by\x18\b \x01(\tR\n" +
	"assignedBy\x12\x1f\n" +
	"\vapproved_by\x18\t \x01(\tR\n" +
	"approvedBy\"\xf8\x01\n" +
	"\"GetMerchantPaymentChannelsResponse\x12s\n" +
	"\x19merchant_payment_channels\x18\x01 \x03(\v27.merchant_payment_channels_proto.MerchantPaymentChannelR\x17merchantPaymentChannels\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xb0\x02\n" +
	"!EditMerchantPaymentChannelRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12,\n" +
	"\x12payment_channel_id\x18\x03 \x01(\tR\x10paymentChannelId\x12'\n" +
	"\x0fapproval_status\x18\x04 \x01(\tR\x0eapprovalStatus\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vassigned_by\x18\x06 \x01(\tR\n" +
	"assignedBy\x12\x1f\n" +
	"\vapproved_by\x18\a \x01(\tR\n" +
	"approvedBy\x12\x0e\n" +
	"\x02id\x18\t \x01(\tR\x02id\"W\n" +
	"$ApproveMerchantPaymentChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\"\x81\x01\n" +
	"#RejectMerchantPaymentChannelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vrejected_by\x18\x02 \x01(\tR\n" +
	"rejectedBy\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReasonBHZF/proto/merchant_payment_channels_proto;merchant_payment_channels_protob\x06proto3"

var (
	file_merchant_payment_channels_proto_rawDescOnce sync.Once
	file_merchant_payment_channels_proto_rawDescData []byte
)

func file_merchant_payment_channels_proto_rawDescGZIP() []byte {
	file_merchant_payment_channels_proto_rawDescOnce.Do(func() {
		file_merchant_payment_channels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_payment_channels_proto_rawDesc), len(file_merchant_payment_channels_proto_rawDesc)))
	})
	return file_merchant_payment_channels_proto_rawDescData
}

var file_merchant_payment_channels_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_merchant_payment_channels_proto_goTypes = []any{
	(*CreateMerchantPaymentChannelRequest)(nil),  // 0: merchant_payment_channels_proto.CreateMerchantPaymentChannelRequest
	(*MerchantPaymentChannel)(nil),               // 1: merchant_payment_channels_proto.MerchantPaymentChannel
	(*GetMerchantPaymentChannelsRequest)(nil),    // 2: merchant_payment_channels_proto.GetMerchantPaymentChannelsRequest
	(*GetMerchantPaymentChannelsResponse)(nil),   // 3: merchant_payment_channels_proto.GetMerchantPaymentChannelsResponse
	(*EditMerchantPaymentChannelRequest)(nil),    // 4: merchant_payment_channels_proto.EditMerchantPaymentChannelRequest
	(*ApproveMerchantPaymentChannelRequest)(nil), // 5: merchant_payment_channels_proto.ApproveMerchantPaymentChannelRequest
	(*RejectMerchantPaymentChannelRequest)(nil),  // 6: merchant_payment_channels_proto.RejectMerchantPaymentChannelRequest
}
var file_merchant_payment_channels_proto_depIdxs = []int32{
	1, // 0: merchant_payment_channels_proto.GetMerchantPaymentChannelsResponse.merchant_payment_channels:type_name -> merchant_payment_channels_proto.MerchantPaymentChannel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_payment_channels_proto_init() }
func file_merchant_payment_channels_proto_init() {
	if File_merchant_payment_channels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_payment_channels_proto_rawDesc), len(file_merchant_payment_channels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_merchant_payment_channels_proto_goTypes,
		DependencyIndexes: file_merchant_payment_channels_proto_depIdxs,
		MessageInfos:      file_merchant_payment_channels_proto_msgTypes,
	}.Build()
	File_merchant_payment_channels_proto = out.File
	file_merchant_payment_channels_proto_goTypes = nil
	file_merchant_payment_channels_proto_depIdxs = nil
}
