// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: batch-name-lookup.proto

package batch_name_lookup_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchNameLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchNameLookupRequest) Reset() {
	*x = BatchNameLookupRequest{}
	mi := &file_batch_name_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchNameLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchNameLookupRequest) ProtoMessage() {}

func (x *BatchNameLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_batch_name_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchNameLookupRequest.ProtoReflect.Descriptor instead.
func (*BatchNameLookupRequest) Descriptor() ([]byte, []int) {
	return file_batch_name_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *BatchNameLookupRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type BatchNameLookupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchNameLookupData) Reset() {
	*x = BatchNameLookupData{}
	mi := &file_batch_name_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchNameLookupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchNameLookupData) ProtoMessage() {}

func (x *BatchNameLookupData) ProtoReflect() protoreflect.Message {
	mi := &file_batch_name_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchNameLookupData.ProtoReflect.Descriptor instead.
func (*BatchNameLookupData) Descriptor() ([]byte, []int) {
	return file_batch_name_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *BatchNameLookupData) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *BatchNameLookupData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BatchNameLookupData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type BatchNameLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*BatchNameLookupData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchNameLookupResponse) Reset() {
	*x = BatchNameLookupResponse{}
	mi := &file_batch_name_lookup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchNameLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchNameLookupResponse) ProtoMessage() {}

func (x *BatchNameLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_batch_name_lookup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchNameLookupResponse.ProtoReflect.Descriptor instead.
func (*BatchNameLookupResponse) Descriptor() ([]byte, []int) {
	return file_batch_name_lookup_proto_rawDescGZIP(), []int{2}
}

func (x *BatchNameLookupResponse) GetData() []*BatchNameLookupData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BatchNameLookupResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *BatchNameLookupResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *BatchNameLookupResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_batch_name_lookup_proto protoreflect.FileDescriptor

const file_batch_name_lookup_proto_rawDesc = "" +
	"\n" +
	"\x17batch-name-lookup.proto\x12\x17batch_name_lookup_proto\"9\n" +
	"\x16BatchNameLookupRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"h\n" +
	"\x13BatchNameLookupData\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"\xba\x01\n" +
	"\x17BatchNameLookupResponse\x12@\n" +
	"\x04data\x18\x01 \x03(\v2,.batch_name_lookup_proto.BatchNameLookupDataR\x04data\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMoreB8Z6/proto/batch_name_lookup_proto;batch_name_lookup_protob\x06proto3"

var (
	file_batch_name_lookup_proto_rawDescOnce sync.Once
	file_batch_name_lookup_proto_rawDescData []byte
)

func file_batch_name_lookup_proto_rawDescGZIP() []byte {
	file_batch_name_lookup_proto_rawDescOnce.Do(func() {
		file_batch_name_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_batch_name_lookup_proto_rawDesc), len(file_batch_name_lookup_proto_rawDesc)))
	})
	return file_batch_name_lookup_proto_rawDescData
}

var file_batch_name_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_batch_name_lookup_proto_goTypes = []any{
	(*BatchNameLookupRequest)(nil),  // 0: batch_name_lookup_proto.BatchNameLookupRequest
	(*BatchNameLookupData)(nil),     // 1: batch_name_lookup_proto.BatchNameLookupData
	(*BatchNameLookupResponse)(nil), // 2: batch_name_lookup_proto.BatchNameLookupResponse
}
var file_batch_name_lookup_proto_depIdxs = []int32{
	1, // 0: batch_name_lookup_proto.BatchNameLookupResponse.data:type_name -> batch_name_lookup_proto.BatchNameLookupData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_batch_name_lookup_proto_init() }
func file_batch_name_lookup_proto_init() {
	if File_batch_name_lookup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_batch_name_lookup_proto_rawDesc), len(file_batch_name_lookup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_batch_name_lookup_proto_goTypes,
		DependencyIndexes: file_batch_name_lookup_proto_depIdxs,
		MessageInfos:      file_batch_name_lookup_proto_msgTypes,
	}.Build()
	File_batch_name_lookup_proto = out.File
	file_batch_name_lookup_proto_goTypes = nil
	file_batch_name_lookup_proto_depIdxs = nil
}
