// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: settlement.proto

package settlementpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettlementService_CalculateSettlement_FullMethodName = "/settlement.SettlementService/CalculateSettlement"
	SettlementService_CreateSettlement_FullMethodName    = "/settlement.SettlementService/CreateSettlement"
	SettlementService_ApproveSettlement_FullMethodName   = "/settlement.SettlementService/ApproveSettlement"
)

// SettlementServiceClient is the client API for SettlementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettlementServiceClient interface {
	CalculateSettlement(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
	CreateSettlement(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
	ApproveSettlement(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
}

type settlementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlementServiceClient(cc grpc.ClientConnInterface) SettlementServiceClient {
	return &settlementServiceClient{cc}
}

func (c *settlementServiceClient) CalculateSettlement(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, SettlementService_CalculateSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementServiceClient) CreateSettlement(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, SettlementService_CreateSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settlementServiceClient) ApproveSettlement(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, SettlementService_ApproveSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettlementServiceServer is the server API for SettlementService service.
// All implementations must embed UnimplementedSettlementServiceServer
// for forward compatibility.
type SettlementServiceServer interface {
	CalculateSettlement(context.Context, *CalculateRequest) (*CalculateResponse, error)
	CreateSettlement(context.Context, *CreateRequest) (*SettlementResponse, error)
	ApproveSettlement(context.Context, *ApproveRequest) (*SettlementResponse, error)
	mustEmbedUnimplementedSettlementServiceServer()
}

// UnimplementedSettlementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettlementServiceServer struct{}

func (UnimplementedSettlementServiceServer) CalculateSettlement(context.Context, *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateSettlement not implemented")
}
func (UnimplementedSettlementServiceServer) CreateSettlement(context.Context, *CreateRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSettlement not implemented")
}
func (UnimplementedSettlementServiceServer) ApproveSettlement(context.Context, *ApproveRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveSettlement not implemented")
}
func (UnimplementedSettlementServiceServer) mustEmbedUnimplementedSettlementServiceServer() {}
func (UnimplementedSettlementServiceServer) testEmbeddedByValue()                           {}

// UnsafeSettlementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettlementServiceServer will
// result in compilation errors.
type UnsafeSettlementServiceServer interface {
	mustEmbedUnimplementedSettlementServiceServer()
}

func RegisterSettlementServiceServer(s grpc.ServiceRegistrar, srv SettlementServiceServer) {
	// If the following call panics, it indicates UnimplementedSettlementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettlementService_ServiceDesc, srv)
}

func _SettlementService_CalculateSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).CalculateSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementService_CalculateSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).CalculateSettlement(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettlementService_CreateSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).CreateSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementService_CreateSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).CreateSettlement(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettlementService_ApproveSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServiceServer).ApproveSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettlementService_ApproveSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServiceServer).ApproveSettlement(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettlementService_ServiceDesc is the grpc.ServiceDesc for SettlementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettlementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settlement.SettlementService",
	HandlerType: (*SettlementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSettlement",
			Handler:    _SettlementService_CalculateSettlement_Handler,
		},
		{
			MethodName: "CreateSettlement",
			Handler:    _SettlementService_CreateSettlement_Handler,
		},
		{
			MethodName: "ApproveSettlement",
			Handler:    _SettlementService_ApproveSettlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settlement.proto",
}
