// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: settlement.proto

package settlementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MerchantIds   []string               `protobuf:"bytes,3,rep,name=merchant_ids,json=merchantIds,proto3" json:"merchant_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CalculateRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CalculateRequest) GetMerchantIds() []string {
	if x != nil {
		return x.MerchantIds
	}
	return nil
}

type CalculateResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StartDate           string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate             string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TotalVolume         float64                `protobuf:"fixed64,3,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	NetSettlementAmount float64                `protobuf:"fixed64,4,opt,name=net_settlement_amount,json=netSettlementAmount,proto3" json:"net_settlement_amount,omitempty"`
	TotalFees           float64                `protobuf:"fixed64,5,opt,name=total_fees,json=totalFees,proto3" json:"total_fees,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CalculateResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CalculateResponse) GetTotalVolume() float64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *CalculateResponse) GetNetSettlementAmount() float64 {
	if x != nil {
		return x.NetSettlementAmount
	}
	return 0
}

func (x *CalculateResponse) GetTotalFees() float64 {
	if x != nil {
		return x.TotalFees
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_settlement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type SettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // e.g. PENDING, APPROVED, REJECTED
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_settlement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{3}
}

func (x *SettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *SettlementResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SettlementResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SettlementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettlementResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	ApproverId    string                 `protobuf:"bytes,2,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_settlement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveRequest) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *ApproveRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

var File_settlement_proto protoreflect.FileDescriptor

const file_settlement_proto_rawDesc = "" +
	"\n" +
	"\x10settlement.proto\x12\n" +
	"settlement\"o\n" +
	"\x10CalculateRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12!\n" +
	"\fmerchant_ids\x18\x03 \x03(\tR\vmerchantIds\"\xc3\x01\n" +
	"\x11CalculateResponse\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12!\n" +
	"\ftotal_volume\x18\x03 \x01(\x01R\vtotalVolume\x122\n" +
	"\x15net_settlement_amount\x18\x04 \x01(\x01R\x13netSettlementAmount\x12\x1d\n" +
	"\n" +
	"total_fees\x18\x05 \x01(\x01R\ttotalFees\"d\n" +
	"\rCreateRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xc5\x01\n" +
	"\x12SettlementResponse\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"V\n" +
	"\x0eApproveRequest\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x1f\n" +
	"\vapprover_id\x18\x02 \x01(\tR\n" +
	"approverId2\x87\x02\n" +
	"\x11SettlementService\x12R\n" +
	"\x13CalculateSettlement\x12\x1c.settlement.CalculateRequest\x1a\x1d.settlement.CalculateResponse\x12M\n" +
	"\x10CreateSettlement\x12\x19.settlement.CreateRequest\x1a\x1e.settlement.SettlementResponse\x12O\n" +
	"\x11ApproveSettlement\x12\x1a.settlement.ApproveRequest\x1a\x1e.settlement.SettlementResponseB8Z6github.com/Cork-Holdings/gp_gateway/proto/settlementpbb\x06proto3"

var (
	file_settlement_proto_rawDescOnce sync.Once
	file_settlement_proto_rawDescData []byte
)

func file_settlement_proto_rawDescGZIP() []byte {
	file_settlement_proto_rawDescOnce.Do(func() {
		file_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)))
	})
	return file_settlement_proto_rawDescData
}

var file_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_settlement_proto_goTypes = []any{
	(*CalculateRequest)(nil),   // 0: settlement.CalculateRequest
	(*CalculateResponse)(nil),  // 1: settlement.CalculateResponse
	(*CreateRequest)(nil),      // 2: settlement.CreateRequest
	(*SettlementResponse)(nil), // 3: settlement.SettlementResponse
	(*ApproveRequest)(nil),     // 4: settlement.ApproveRequest
}
var file_settlement_proto_depIdxs = []int32{
	0, // 0: settlement.SettlementService.CalculateSettlement:input_type -> settlement.CalculateRequest
	2, // 1: settlement.SettlementService.CreateSettlement:input_type -> settlement.CreateRequest
	4, // 2: settlement.SettlementService.ApproveSettlement:input_type -> settlement.ApproveRequest
	1, // 3: settlement.SettlementService.CalculateSettlement:output_type -> settlement.CalculateResponse
	3, // 4: settlement.SettlementService.CreateSettlement:output_type -> settlement.SettlementResponse
	3, // 5: settlement.SettlementService.ApproveSettlement:output_type -> settlement.SettlementResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settlement_proto_init() }
func file_settlement_proto_init() {
	if File_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_proto_goTypes,
		DependencyIndexes: file_settlement_proto_depIdxs,
		MessageInfos:      file_settlement_proto_msgTypes,
	}.Build()
	File_settlement_proto = out.File
	file_settlement_proto_goTypes = nil
	file_settlement_proto_depIdxs = nil
}
