// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: subscriptions.proto

package subscriptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Subscription) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscriptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSubscriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSubscriptionsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  []*Subscription        `protobuf:"bytes,1,rep,name=subscription,proto3" json:"subscription,omitempty"`                   // List of subscriptions
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`    // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`             // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionsResponse) GetSubscription() []*Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *GetSubscriptionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetSubscriptionsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetSubscriptionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSubscriptionRequest) Reset() {
	*x = EditSubscriptionRequest{}
	mi := &file_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSubscriptionRequest) ProtoMessage() {}

func (x *EditSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*EditSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *EditSubscriptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditSubscriptionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditSubscriptionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateMerchantSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMerchantSubscriptionRequest) Reset() {
	*x = CreateMerchantSubscriptionRequest{}
	mi := &file_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantSubscriptionRequest) ProtoMessage() {}

func (x *CreateMerchantSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMerchantSubscriptionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CreateMerchantSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CreateMerchantSubscriptionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MerchantSubscription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Id             string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MerchantSubscription) Reset() {
	*x = MerchantSubscription{}
	mi := &file_subscriptions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantSubscription) ProtoMessage() {}

func (x *MerchantSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantSubscription.ProtoReflect.Descriptor instead.
func (*MerchantSubscription) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantSubscription) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantSubscription) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *MerchantSubscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantSubscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantSubscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantSubscription) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMerchantSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantSubscriptionsRequest) Reset() {
	*x = GetMerchantSubscriptionsRequest{}
	mi := &file_subscriptions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantSubscriptionsRequest) ProtoMessage() {}

func (x *GetMerchantSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchantSubscriptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMerchantSubscriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMerchantSubscriptionsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type GetMerchantSubscriptionsResponse struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	MerchantSubscription []*MerchantSubscription `protobuf:"bytes,1,rep,name=merchant_subscription,json=merchantSubscription,proto3" json:"merchant_subscription,omitempty"` // List of merchant subscriptions
	TotalPages           int32                   `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                              // Total number of pages
	CurrentPage          int32                   `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`                           // Current page
	HasMore              bool                    `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                                       // Whether there are more pages
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetMerchantSubscriptionsResponse) Reset() {
	*x = GetMerchantSubscriptionsResponse{}
	mi := &file_subscriptions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantSubscriptionsResponse) ProtoMessage() {}

func (x *GetMerchantSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{8}
}

func (x *GetMerchantSubscriptionsResponse) GetMerchantSubscription() []*MerchantSubscription {
	if x != nil {
		return x.MerchantSubscription
	}
	return nil
}

func (x *GetMerchantSubscriptionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetMerchantSubscriptionsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetMerchantSubscriptionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditMerchantSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMerchantSubscriptionRequest) Reset() {
	*x = EditMerchantSubscriptionRequest{}
	mi := &file_subscriptions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMerchantSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMerchantSubscriptionRequest) ProtoMessage() {}

func (x *EditMerchantSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMerchantSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*EditMerchantSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{9}
}

func (x *EditMerchantSubscriptionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *EditMerchantSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *EditMerchantSubscriptionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteMerchantSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteMerchantSubscriptionRequest) Reset() {
	*x = DeleteMerchantSubscriptionRequest{}
	mi := &file_subscriptions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantSubscriptionRequest) ProtoMessage() {}

func (x *DeleteMerchantSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteMerchantSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMerchantSubscriptionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *DeleteMerchantSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

var File_subscriptions_proto protoreflect.FileDescriptor

const file_subscriptions_proto_rawDesc = "" +
	"\n" +
	"\x13subscriptions.proto\x12\rsubscriptions\"[\n" +
	"\x19CreateSubscriptionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x9c\x01\n" +
	"\fSubscription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"m\n" +
	"\x17GetSubscriptionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xba\x01\n" +
	"\x18GetSubscriptionsResponse\x12?\n" +
	"\fsubscription\x18\x01 \x03(\v2\x1b.subscriptions.SubscriptionR\fsubscription\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"Y\n" +
	"\x17EditSubscriptionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\x85\x01\n" +
	"!CreateMerchantSubscriptionRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xc6\x01\n" +
	"\x14MerchantSubscription\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"u\n" +
	"\x1fGetMerchantSubscriptionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"\xdb\x01\n" +
	" GetMerchantSubscriptionsResponse\x12X\n" +
	"\x15merchant_subscription\x18\x01 \x03(\v2#.subscriptions.MerchantSubscriptionR\x14merchantSubscription\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\x83\x01\n" +
	"\x1fEditMerchantSubscriptionRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"m\n" +
	"!DeleteMerchantSubscriptionRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionIdB$Z\"/proto/subscriptions;subscriptionsb\x06proto3"

var (
	file_subscriptions_proto_rawDescOnce sync.Once
	file_subscriptions_proto_rawDescData []byte
)

func file_subscriptions_proto_rawDescGZIP() []byte {
	file_subscriptions_proto_rawDescOnce.Do(func() {
		file_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscriptions_proto_rawDesc), len(file_subscriptions_proto_rawDesc)))
	})
	return file_subscriptions_proto_rawDescData
}

var file_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_subscriptions_proto_goTypes = []any{
	(*CreateSubscriptionRequest)(nil),         // 0: subscriptions.CreateSubscriptionRequest
	(*Subscription)(nil),                      // 1: subscriptions.Subscription
	(*GetSubscriptionsRequest)(nil),           // 2: subscriptions.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),          // 3: subscriptions.GetSubscriptionsResponse
	(*EditSubscriptionRequest)(nil),           // 4: subscriptions.EditSubscriptionRequest
	(*CreateMerchantSubscriptionRequest)(nil), // 5: subscriptions.CreateMerchantSubscriptionRequest
	(*MerchantSubscription)(nil),              // 6: subscriptions.MerchantSubscription
	(*GetMerchantSubscriptionsRequest)(nil),   // 7: subscriptions.GetMerchantSubscriptionsRequest
	(*GetMerchantSubscriptionsResponse)(nil),  // 8: subscriptions.GetMerchantSubscriptionsResponse
	(*EditMerchantSubscriptionRequest)(nil),   // 9: subscriptions.EditMerchantSubscriptionRequest
	(*DeleteMerchantSubscriptionRequest)(nil), // 10: subscriptions.DeleteMerchantSubscriptionRequest
}
var file_subscriptions_proto_depIdxs = []int32{
	1, // 0: subscriptions.GetSubscriptionsResponse.subscription:type_name -> subscriptions.Subscription
	6, // 1: subscriptions.GetMerchantSubscriptionsResponse.merchant_subscription:type_name -> subscriptions.MerchantSubscription
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_subscriptions_proto_init() }
func file_subscriptions_proto_init() {
	if File_subscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscriptions_proto_rawDesc), len(file_subscriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscriptions_proto_goTypes,
		DependencyIndexes: file_subscriptions_proto_depIdxs,
		MessageInfos:      file_subscriptions_proto_msgTypes,
	}.Build()
	File_subscriptions_proto = out.File
	file_subscriptions_proto_goTypes = nil
	file_subscriptions_proto_depIdxs = nil
}
