// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: kyc.proto

package kycpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DocumentType  string                 `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"` // e.g. PASSPORT, INC_CERT
	DocumentUrl   string                 `protobuf:"bytes,3,opt,name=document_url,json=documentUrl,proto3" json:"document_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadDocumentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *UploadDocumentRequest) GetDocumentUrl() string {
	if x != nil {
		return x.DocumentUrl
	}
	return ""
}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // e.g. UPLOADED, SCANNING, VERIFIED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UploadDocumentResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type KYCStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KYCStatusRequest) Reset() {
	*x = KYCStatusRequest{}
	mi := &file_kyc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCStatusRequest) ProtoMessage() {}

func (x *KYCStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCStatusRequest.ProtoReflect.Descriptor instead.
func (*KYCStatusRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{2}
}

func (x *KYCStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type KYCStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g. PENDING, APPROVED, REJECTED
	LastUpdated   string                 `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KYCStatusResponse) Reset() {
	*x = KYCStatusResponse{}
	mi := &file_kyc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KYCStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KYCStatusResponse) ProtoMessage() {}

func (x *KYCStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KYCStatusResponse.ProtoReflect.Descriptor instead.
func (*KYCStatusResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{3}
}

func (x *KYCStatusResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *KYCStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KYCStatusResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type AMLScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetName    string                 `protobuf:"bytes,1,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	TargetType    string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // e.g. INDIVIDUAL, ENTITY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLScanRequest) Reset() {
	*x = AMLScanRequest{}
	mi := &file_kyc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLScanRequest) ProtoMessage() {}

func (x *AMLScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLScanRequest.ProtoReflect.Descriptor instead.
func (*AMLScanRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{4}
}

func (x *AMLScanRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *AMLScanRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

type AMLScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // e.g. PASSED, FLAGGED
	MatchScore    float64                `protobuf:"fixed64,3,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMLScanResponse) Reset() {
	*x = AMLScanResponse{}
	mi := &file_kyc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMLScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMLScanResponse) ProtoMessage() {}

func (x *AMLScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMLScanResponse.ProtoReflect.Descriptor instead.
func (*AMLScanResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{5}
}

func (x *AMLScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *AMLScanResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AMLScanResponse) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

var File_kyc_proto protoreflect.FileDescriptor

const file_kyc_proto_rawDesc = "" +
	"\n" +
	"\tkyc.proto\x12\x03kyc\"|\n" +
	"\x15UploadDocumentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rdocument_type\x18\x02 \x01(\tR\fdocumentType\x12!\n" +
	"\fdocument_url\x18\x03 \x01(\tR\vdocumentUrl\"n\n" +
	"\x16UploadDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"/\n" +
	"\x10KYCStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"k\n" +
	"\x11KYCStatusResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\flast_updated\x18\x03 \x01(\tR\vlastUpdated\"R\n" +
	"\x0eAMLScanRequest\x12\x1f\n" +
	"\vtarget_name\x18\x01 \x01(\tR\n" +
	"targetName\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\"c\n" +
	"\x0fAMLScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1f\n" +
	"\vmatch_score\x18\x03 \x01(\x01R\n" +
	"matchScore2\xd6\x01\n" +
	"\n" +
	"KYCService\x12L\n" +
	"\x11UploadKYCDocument\x12\x1a.kyc.UploadDocumentRequest\x1a\x1b.kyc.UploadDocumentResponse\x12=\n" +
	"\fGetKYCStatus\x12\x15.kyc.KYCStatusRequest\x1a\x16.kyc.KYCStatusResponse\x12;\n" +
	"\x0ePerformAMLScan\x12\x13.kyc.AMLScanRequest\x1a\x14.kyc.AMLScanResponseB?Z=github.com/Cork-Holdings/gp_payment_orchestration/proto/kycpbb\x06proto3"

var (
	file_kyc_proto_rawDescOnce sync.Once
	file_kyc_proto_rawDescData []byte
)

func file_kyc_proto_rawDescGZIP() []byte {
	file_kyc_proto_rawDescOnce.Do(func() {
		file_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_proto_rawDesc), len(file_kyc_proto_rawDesc)))
	})
	return file_kyc_proto_rawDescData
}

var file_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kyc_proto_goTypes = []any{
	(*UploadDocumentRequest)(nil),  // 0: kyc.UploadDocumentRequest
	(*UploadDocumentResponse)(nil), // 1: kyc.UploadDocumentResponse
	(*KYCStatusRequest)(nil),       // 2: kyc.KYCStatusRequest
	(*KYCStatusResponse)(nil),      // 3: kyc.KYCStatusResponse
	(*AMLScanRequest)(nil),         // 4: kyc.AMLScanRequest
	(*AMLScanResponse)(nil),        // 5: kyc.AMLScanResponse
}
var file_kyc_proto_depIdxs = []int32{
	0, // 0: kyc.KYCService.UploadKYCDocument:input_type -> kyc.UploadDocumentRequest
	2, // 1: kyc.KYCService.GetKYCStatus:input_type -> kyc.KYCStatusRequest
	4, // 2: kyc.KYCService.PerformAMLScan:input_type -> kyc.AMLScanRequest
	1, // 3: kyc.KYCService.UploadKYCDocument:output_type -> kyc.UploadDocumentResponse
	3, // 4: kyc.KYCService.GetKYCStatus:output_type -> kyc.KYCStatusResponse
	5, // 5: kyc.KYCService.PerformAMLScan:output_type -> kyc.AMLScanResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kyc_proto_init() }
func file_kyc_proto_init() {
	if File_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_proto_rawDesc), len(file_kyc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyc_proto_goTypes,
		DependencyIndexes: file_kyc_proto_depIdxs,
		MessageInfos:      file_kyc_proto_msgTypes,
	}.Build()
	File_kyc_proto = out.File
	file_kyc_proto_goTypes = nil
	file_kyc_proto_depIdxs = nil
}
