// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: float.proto

package floatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FloatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Remarks       string                 `protobuf:"bytes,4,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatRequest) Reset() {
	*x = FloatRequest{}
	mi := &file_float_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatRequest) ProtoMessage() {}

func (x *FloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_float_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatRequest.ProtoReflect.Descriptor instead.
func (*FloatRequest) Descriptor() ([]byte, []int) {
	return file_float_proto_rawDescGZIP(), []int{0}
}

func (x *FloatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FloatRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FloatRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FloatRequest) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

type FloatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // e.g. PENDING, APPROVED, REJECTED
	Remarks       string                 `protobuf:"bytes,6,opt,name=remarks,proto3" json:"remarks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatResponse) Reset() {
	*x = FloatResponse{}
	mi := &file_float_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatResponse) ProtoMessage() {}

func (x *FloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_float_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatResponse.ProtoReflect.Descriptor instead.
func (*FloatResponse) Descriptor() ([]byte, []int) {
	return file_float_proto_rawDescGZIP(), []int{1}
}

func (x *FloatResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FloatResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FloatResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FloatResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FloatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FloatResponse) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *FloatResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ApproveFloatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApproverId    string                 `protobuf:"bytes,2,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveFloatRequest) Reset() {
	*x = ApproveFloatRequest{}
	mi := &file_float_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveFloatRequest) ProtoMessage() {}

func (x *ApproveFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_float_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveFloatRequest.ProtoReflect.Descriptor instead.
func (*ApproveFloatRequest) Descriptor() ([]byte, []int) {
	return file_float_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveFloatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApproveFloatRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

type FloatBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatBalanceRequest) Reset() {
	*x = FloatBalanceRequest{}
	mi := &file_float_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatBalanceRequest) ProtoMessage() {}

func (x *FloatBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_float_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatBalanceRequest.ProtoReflect.Descriptor instead.
func (*FloatBalanceRequest) Descriptor() ([]byte, []int) {
	return file_float_proto_rawDescGZIP(), []int{3}
}

func (x *FloatBalanceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type FloatBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatBalanceResponse) Reset() {
	*x = FloatBalanceResponse{}
	mi := &file_float_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatBalanceResponse) ProtoMessage() {}

func (x *FloatBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_float_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatBalanceResponse.ProtoReflect.Descriptor instead.
func (*FloatBalanceResponse) Descriptor() ([]byte, []int) {
	return file_float_proto_rawDescGZIP(), []int{4}
}

func (x *FloatBalanceResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FloatBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *FloatBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_float_proto protoreflect.FileDescriptor

const file_float_proto_rawDesc = "" +
	"\n" +
	"\vfloat.proto\x12\x05float\"y\n" +
	"\fFloatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\aremarks\x18\x04 \x01(\tR\aremarks\"\xd0\x01\n" +
	"\rFloatResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\aremarks\x18\x06 \x01(\tR\aremarks\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"U\n" +
	"\x13ApproveFloatRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vapprover_id\x18\x02 \x01(\tR\n" +
	"approverId\"2\n" +
	"\x13FloatBalanceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"i\n" +
	"\x14FloatBalanceResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency2\xd7\x01\n" +
	"\fFloatService\x129\n" +
	"\fRequestFloat\x12\x13.float.FloatRequest\x1a\x14.float.FloatResponse\x12@\n" +
	"\fApproveFloat\x12\x1a.float.ApproveFloatRequest\x1a\x14.float.FloatResponse\x12J\n" +
	"\x0fGetFloatBalance\x12\x1a.float.FloatBalanceRequest\x1a\x1b.float.FloatBalanceResponseB3Z1github.com/Cork-Holdings/gp_gateway/proto/floatpbb\x06proto3"

var (
	file_float_proto_rawDescOnce sync.Once
	file_float_proto_rawDescData []byte
)

func file_float_proto_rawDescGZIP() []byte {
	file_float_proto_rawDescOnce.Do(func() {
		file_float_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_float_proto_rawDesc), len(file_float_proto_rawDesc)))
	})
	return file_float_proto_rawDescData
}

var file_float_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_float_proto_goTypes = []any{
	(*FloatRequest)(nil),         // 0: float.FloatRequest
	(*FloatResponse)(nil),        // 1: float.FloatResponse
	(*ApproveFloatRequest)(nil),  // 2: float.ApproveFloatRequest
	(*FloatBalanceRequest)(nil),  // 3: float.FloatBalanceRequest
	(*FloatBalanceResponse)(nil), // 4: float.FloatBalanceResponse
}
var file_float_proto_depIdxs = []int32{
	0, // 0: float.FloatService.RequestFloat:input_type -> float.FloatRequest
	2, // 1: float.FloatService.ApproveFloat:input_type -> float.ApproveFloatRequest
	3, // 2: float.FloatService.GetFloatBalance:input_type -> float.FloatBalanceRequest
	1, // 3: float.FloatService.RequestFloat:output_type -> float.FloatResponse
	1, // 4: float.FloatService.ApproveFloat:output_type -> float.FloatResponse
	4, // 5: float.FloatService.GetFloatBalance:output_type -> float.FloatBalanceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_float_proto_init() }
func file_float_proto_init() {
	if File_float_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_float_proto_rawDesc), len(file_float_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_float_proto_goTypes,
		DependencyIndexes: file_float_proto_depIdxs,
		MessageInfos:      file_float_proto_msgTypes,
	}.Build()
	File_float_proto = out.File
	file_float_proto_goTypes = nil
	file_float_proto_depIdxs = nil
}
