// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: float.proto

package floatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FloatService_RequestFloat_FullMethodName    = "/float.FloatService/RequestFloat"
	FloatService_ApproveFloat_FullMethodName    = "/float.FloatService/ApproveFloat"
	FloatService_GetFloatBalance_FullMethodName = "/float.FloatService/GetFloatBalance"
)

// FloatServiceClient is the client API for FloatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FloatServiceClient interface {
	RequestFloat(ctx context.Context, in *FloatRequest, opts ...grpc.CallOption) (*FloatResponse, error)
	ApproveFloat(ctx context.Context, in *ApproveFloatRequest, opts ...grpc.CallOption) (*FloatResponse, error)
	GetFloatBalance(ctx context.Context, in *FloatBalanceRequest, opts ...grpc.CallOption) (*FloatBalanceResponse, error)
}

type floatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFloatServiceClient(cc grpc.ClientConnInterface) FloatServiceClient {
	return &floatServiceClient{cc}
}

func (c *floatServiceClient) RequestFloat(ctx context.Context, in *FloatRequest, opts ...grpc.CallOption) (*FloatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloatResponse)
	err := c.cc.Invoke(ctx, FloatService_RequestFloat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *floatServiceClient) ApproveFloat(ctx context.Context, in *ApproveFloatRequest, opts ...grpc.CallOption) (*FloatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloatResponse)
	err := c.cc.Invoke(ctx, FloatService_ApproveFloat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *floatServiceClient) GetFloatBalance(ctx context.Context, in *FloatBalanceRequest, opts ...grpc.CallOption) (*FloatBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloatBalanceResponse)
	err := c.cc.Invoke(ctx, FloatService_GetFloatBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FloatServiceServer is the server API for FloatService service.
// All implementations must embed UnimplementedFloatServiceServer
// for forward compatibility.
type FloatServiceServer interface {
	RequestFloat(context.Context, *FloatRequest) (*FloatResponse, error)
	ApproveFloat(context.Context, *ApproveFloatRequest) (*FloatResponse, error)
	GetFloatBalance(context.Context, *FloatBalanceRequest) (*FloatBalanceResponse, error)
	mustEmbedUnimplementedFloatServiceServer()
}

// UnimplementedFloatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFloatServiceServer struct{}

func (UnimplementedFloatServiceServer) RequestFloat(context.Context, *FloatRequest) (*FloatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFloat not implemented")
}
func (UnimplementedFloatServiceServer) ApproveFloat(context.Context, *ApproveFloatRequest) (*FloatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveFloat not implemented")
}
func (UnimplementedFloatServiceServer) GetFloatBalance(context.Context, *FloatBalanceRequest) (*FloatBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFloatBalance not implemented")
}
func (UnimplementedFloatServiceServer) mustEmbedUnimplementedFloatServiceServer() {}
func (UnimplementedFloatServiceServer) testEmbeddedByValue()                      {}

// UnsafeFloatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FloatServiceServer will
// result in compilation errors.
type UnsafeFloatServiceServer interface {
	mustEmbedUnimplementedFloatServiceServer()
}

func RegisterFloatServiceServer(s grpc.ServiceRegistrar, srv FloatServiceServer) {
	// If the following call panics, it indicates UnimplementedFloatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FloatService_ServiceDesc, srv)
}

func _FloatService_RequestFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FloatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloatServiceServer).RequestFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FloatService_RequestFloat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloatServiceServer).RequestFloat(ctx, req.(*FloatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FloatService_ApproveFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveFloatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloatServiceServer).ApproveFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FloatService_ApproveFloat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloatServiceServer).ApproveFloat(ctx, req.(*ApproveFloatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FloatService_GetFloatBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FloatBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloatServiceServer).GetFloatBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FloatService_GetFloatBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloatServiceServer).GetFloatBalance(ctx, req.(*FloatBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FloatService_ServiceDesc is the grpc.ServiceDesc for FloatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FloatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "float.FloatService",
	HandlerType: (*FloatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestFloat",
			Handler:    _FloatService_RequestFloat_Handler,
		},
		{
			MethodName: "ApproveFloat",
			Handler:    _FloatService_ApproveFloat_Handler,
		},
		{
			MethodName: "GetFloatBalance",
			Handler:    _FloatService_GetFloatBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "float.proto",
}
